# yapf: disable

from unicon.defs import n1
grmini = dict(
    NAME='grmini',
    DOF_NAMES=n1.DOF_NAMES,
    DOF_NAMES_STD=n1.DOF_NAMES_STD,
    KP=n1.KP,
    KD=n1.KD,
    NUM_DOFS=n1.NUM_DOFS,
    URDF='GRMini1T1/urdf/GRMini1T1_full.urdf',
)

m001 = dict(
    NAME='m001',
    # DOF_NAMES=[

    # ],
    DOF_NAMES_STD={
        'left_leg_hip_yaw_joint': 'left_hip_yaw',
        'left_leg_hip_roll_joint': 'left_hip_roll',
        'left_leg_hip_pitch_joint': 'left_hip_pitch',
        'left_leg_knee_pitch_joint': 'left_knee_pitch',
        'left_leg_ankle_pitch_joint': 'left_ankle_pitch',
        'left_leg_ankle_roll_joint': 'left_ankle_roll',
        'right_leg_hip_yaw_joint': 'right_hip_yaw',
        'right_leg_hip_roll_joint': 'right_hip_roll',
        'right_leg_hip_pitch_joint': 'right_hip_pitch',
        'right_leg_knee_pitch_joint': 'right_knee_pitch',
        'right_leg_ankle_pitch_joint': 'right_ankle_pitch',
        # 'right_leg_ankle_roll_jonit': 'right_ankle_roll',
        'right_leg_ankle_roll_joint': 'right_ankle_roll',
        'left_arm_shoulder_pitch_joint': 'left_shoulder_pitch',
        'left_arm_shoulder_roll_joint': 'left_shoulder_roll',
        'left_arm_elbow_roll_joint': 'left_wrist_roll',
        'right_arm_shoulder_pitch_joint': 'right_shoulder_pitch',
        'right_arm_shoulder_roll_joint': 'right_shoulder_roll',
        'right_arm_elbow_roll_joint': 'right_wrist_roll',
    },
    URDF='m001/m001-0523-05_proc.urdf',
    # KP=[
    #     7.50, 7.00, 7.0, 7.0, 2.00, 2.00,
    #     7.50, 7.00, 7.0, 7.0, 2.00, 2.00,
    #     1.80, .90, .90, .90, .70, .70, .70,
    #     1.80, .90, .90, .90, .70, .70, .70,
    # ],
    # KD=[
    #     .61, 0.60, .61, .61, .125, .10,
    #     .61, 0.60, .61, .61, .125, .10,
    #     .10, .10, .10, .10, .05, .05, .05,
    #     .10, .10, .10, .10, .05, .05, .05,
    # ],
    KP={'joint': 22.},
    KD={'joint': 12.},
)

mini = dict(
    NAME='mini',
    # DOF_NAMES=[

    # ],
    DOF_NAMES_STD={
        'left_leg_hip_yaw_joint': 'left_hip_yaw',
        'left_leg_hip_roll_joint': 'left_hip_roll',
        'left_leg_hip_pitch_joint': 'left_hip_pitch',
        'left_leg_knee_pitch_joint': 'left_knee_pitch',
        'left_leg_ankle_pitch_joint': 'left_ankle_pitch',
        'left_leg_ankle_roll_joint': 'left_ankle_roll',
        'right_leg_hip_yaw_joint': 'right_hip_yaw',
        'right_leg_hip_roll_joint': 'right_hip_roll',
        'right_leg_hip_pitch_joint': 'right_hip_pitch',
        'right_leg_knee_pitch_joint': 'right_knee_pitch',
        'right_leg_ankle_pitch_joint': 'right_ankle_pitch',
        # 'right_leg_ankle_roll_jonit': 'right_ankle_roll',
        'right_leg_ankle_roll_joint': 'right_ankle_roll',
        'left_arm_shoulder_pitch_joint': 'left_shoulder_pitch',
        'left_arm_shoulder_roll_joint': 'left_shoulder_roll',
        'left_arm_elbow_roll_joint': 'left_wrist_roll',
        'right_arm_shoulder_pitch_joint': 'right_shoulder_pitch',
        'right_arm_shoulder_roll_joint': 'right_shoulder_roll',
        'right_arm_elbow_roll_joint': 'right_wrist_roll',
    },
    URDF='mini_v1/urdf/mini_v1.urdf',
    # KP=[
    #     7.50, 7.00, 7.0, 7.0, 2.00, 2.00,
    #     7.50, 7.00, 7.0, 7.0, 2.00, 2.00,
    #     1.80, .90, .90, .90, .70, .70, .70,
    #     1.80, .90, .90, .90, .70, .70, .70,
    # ],
    # KD=[
    #     .61, 0.60, .61, .61, .125, .10,
    #     .61, 0.60, .61, .61, .125, .10,
    #     .10, .10, .10, .10, .05, .05, .05,
    #     .10, .10, .10, .10, .05, .05, .05,
    # ],
    KP={'joint': 22.},
    KD={'joint': 12.},
)

matrix = dict(
    NAME='matrix',
    DOF_NAMES=[
        'L_Leg_Roll',
        'L_Leg_Pitch',
        'L_Leg_Yaw',
        'L_Knees',
        'L_Foot_Pitch',
        'L_Foot_Roll',
        'R_Leg_Roll',
        'R_Leg_Pitch',
        'R_Leg_Yaw',
        'R_Knees',
        'R_Foot_Pitch',
        'R_Foot_Roll',
        'L_Shoulder_Pitch',
        'L_Arm_Roll',
        'L_Arm_Yaw',
        'L_Forearm_Pitch',
        'L_Forearm_Yaw',
        'L_Hand_Pitch',
        'L_Hand_Roll',
        'R_Shoulder_Pitch',
        'R_Arm_Roll',
        'R_Arm_Yaw',
        'R_Forearm_Pitch',
        'R_Forearm_Yaw',
        'R_Hand_Pitch',
        'R_Hand_Roll',
        'Waist_Yaw',
        'Waist_Roll',
        'Waist_Pitch',
        'Head_Pitch_Lower',
        'Head_Roll',
        'Head_Pitch_Upper',
        'Head_Yaw',
    ],
    DOF_NAMES_STD={
        'Waist_Yaw': 'waist_yaw',
        'Waist_Roll': 'waist_roll',
        'Waist_Pitch': 'waist_pitch',
        'L_Shoulder_Pitch': 'left_shoulder_pitch',
        'L_Arm_Roll': 'left_shoulder_roll',
        'L_Arm_Yaw': 'left_shoulder_yaw',
        'L_Forearm_Pitch': 'left_elbow_pitch',
        'L_Forearm_Yaw': 'left_wrist_yaw',
        'L_Hand_Pitch': 'left_wrist_pitch',
        'L_Hand_Roll': 'left_wrist_roll',
        'R_Shoulder_Pitch': 'right_shoulder_pitch',
        'R_Arm_Roll': 'right_shoulder_roll',
        'R_Arm_Yaw': 'right_shoulder_yaw',
        'R_Forearm_Pitch': 'right_elbow_pitch',
        'R_Forearm_Yaw': 'right_wrist_yaw',
        'R_Hand_Pitch': 'right_wrist_pitch',
        'R_Hand_Roll': 'right_wrist_roll',
        # 'Head_Pitch_Lower': 'head_pitch_lower',
        'Head_Pitch_Lower': 'head_pitch',
        'Head_Roll': 'head_roll',
        'Head_Pitch_Upper': 'head_pitch_upper',
        'Head_Yaw': 'head_yaw',
        'L_Leg_Roll': 'left_hip_roll',
        'L_Leg_Pitch': 'left_hip_pitch',
        'L_Leg_Yaw': 'left_hip_yaw',
        'L_Knees': 'left_knee_pitch',
        'L_Foot_Pitch': 'left_ankle_pitch',
        'L_Foot_Roll': 'left_ankle_roll',
        'R_Leg_Roll': 'right_hip_roll',
        'R_Leg_Pitch': 'right_hip_pitch',
        'R_Leg_Yaw': 'right_hip_yaw',
        'R_Knees': 'right_knee_pitch',
        'R_Foot_Pitch': 'right_ankle_pitch',
        'R_Foot_Roll': 'right_ankle_roll',
    },
    # URDF='MatrixRobot/urdf/MatrixRobot.urdf',
    URDF='MatrixRobot/urdf/MatrixRobot_proc.urdf',
    # KP={'_': 100.},
    # KD={'_': 6.},
    KP=[
        400, 400, 200, 450, 400, 100,
        400, 400, 200, 450, 400, 100,
        100, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100, 100, 100, 100,
        200, 400, 400,
        40, 40, 40, 40,
    ],
    KD=[
        40,40,20,45,60,15,
        40,40,20,45,60,15,
        12,12,12,12,12,12,12,
        12,12,12,12,12,12,12,
        40,40,40,
        4,4,4,4,
    ],
    TAU_LIMIT=[
        270,270,80,270,100,100,
        270,270,80,270,100,100,
        40,40,40,40,40,40,40,
        40,40,40,40,40,40,40,
        270,160,160,
        3.3,3.3,3.3,3.3
    ],
    Q_RESET={
        'L_Arm_Roll': -0.6,
        'R_Arm_Roll': 0.6,
    },
)

oghr = dict(
    NAME='oghr',
    URDF='OGHR/urdf/OGHR_wholeBody_1_proc.urdf',
    DOF_NAMES=[
        'Joint-head',
        'Joint-waist-pitch',
        'Joint-waist-roll',
        'Joint-waist-yaw',
        'Joint-hip-r-roll',
        'Joint-hip-r-yaw',
        'Joint-hip-r-pitch',
        'Joint-knee-r-pitch',
        'Joint-ankle-r-pitch',
        'Joint-ankle-r-roll',
        'Joint-hip-l-roll',
        'Joint-hip-l-yaw',
        'Joint-hip-l-pitch',
        'Joint-knee-l-pitch',
        'Joint-ankle-l-pitch',
        'Joint-ankle-l-roll',
        'Joint-arm-l-01',
        'Joint-arm-l-02',
        'Joint-arm-l-03',
        'Joint-arm-l-04',
        'Joint-arm-l-05',
        'Joint-arm-l-06',
        'Joint-arm-l-07',
        'Joint-arm-r-01',
        'Joint-arm-r-02',
        'Joint-arm-r-03',
        'Joint-arm-r-04',
        'Joint-arm-r-05',
        'Joint-arm-r-06',
        'Joint-arm-r-07',
    ],
    DOF_NAMES_STD={
        'Joint-head': 'head_yaw',
        'Joint-waist-pitch': 'waist_pitch',
        'Joint-waist-roll': 'waist_roll',
        'Joint-waist-yaw': 'waist_yaw',
        'Joint-hip-r-roll': 'right_hip_roll',
        'Joint-hip-r-yaw': 'right_hip_yaw',
        'Joint-hip-r-pitch': 'right_hip_pitch',
        'Joint-knee-r-pitch': 'right_knee_pitch',
        'Joint-ankle-r-pitch': 'right_ankle_pitch',
        'Joint-ankle-r-roll': 'right_ankle_roll',
        'Joint-hip-l-roll': 'left_hip_roll',
        'Joint-hip-l-yaw': 'left_hip_yaw',
        'Joint-hip-l-pitch': 'left_hip_pitch',
        'Joint-knee-l-pitch': 'left_knee_pitch',
        'Joint-ankle-l-pitch': 'left_ankle_pitch',
        'Joint-ankle-l-roll': 'left_ankle_roll',
        'Joint-arm-l-01': 'left_shoulder_pitch',
        'Joint-arm-l-02': 'left_shoulder_roll',
        'Joint-arm-l-03': 'left_shoulder_yaw',
        'Joint-arm-l-04': 'left_elbow_pitch',
        'Joint-arm-l-05': 'left_wrist_yaw',
        'Joint-arm-l-06': 'left_wrist_pitch',
        'Joint-arm-l-07': 'left_wrist_roll',
        'Joint-arm-r-01': 'right_shoulder_pitch',
        'Joint-arm-r-02': 'right_shoulder_roll',
        'Joint-arm-r-03': 'right_shoulder_yaw',
        'Joint-arm-r-04': 'right_elbow_pitch',
        'Joint-arm-r-05': 'right_wrist_yaw',
        'Joint-arm-r-06': 'right_wrist_pitch',
        'Joint-arm-r-07': 'right_wrist_roll',
    },
    KP={
        'Joint-hip-r-roll': 300.,
        'Joint-hip-r-yaw': 200.,
        'Joint-hip-r-pitch': 200.,
        'Joint-knee-r-pitch': 400.,
        'Joint-ankle-r-pitch': 120.,
        'Joint-ankle-r-roll': 120.,
        'Joint-hip-l-roll': 300.,
        'Joint-hip-l-yaw': 200.,
        'Joint-hip-l-pitch': 200.,
        'Joint-knee-l-pitch': 400.,
        'Joint-ankle-l-pitch': 120.,
        'Joint-ankle-l-roll': 120.,
        'arm': 200.,
        'head': 100.,
        'waist': 6000.,
    },
    KD={
        'Joint-hip-r-roll': 1.,
        'Joint-hip-r-yaw': 0.5,
        'Joint-hip-r-pitch': 1.,
        'Joint-knee-r-pitch': 4.,
        'Joint-ankle-r-pitch': 1.,
        'Joint-ankle-r-roll': 1.,
        'Joint-hip-l-roll': 1.,
        'Joint-hip-l-yaw': 0.5,
        'Joint-hip-l-pitch': 1.,
        'Joint-knee-l-pitch': 4.,
        'Joint-ankle-l-pitch': 1.,
        'Joint-ankle-l-roll': 1.,
        'arm': 20.,
        'head': 30.,
        'waist': 40.,
    },
    Q_RESET={
        'Joint-arm-r-02': -1.4,
        'Joint-arm-l-02': 1.4,
        'Joint-hip-r-pitch': 0.305913,
        'Joint-knee-r-pitch': -0.670418,
        'Joint-ankle-r-pitch': 0.371265,
        'Joint-hip-l-pitch': 0.305913,
        'Joint-knee-l-pitch': -0.670418,
        'Joint-ankle-l-pitch': 0.371265,
    },
)

loong = dict(
    NAME='loong',
    DOF_NAMES=[
        'J_arm_l_01', 'J_arm_l_02', 'J_arm_l_03', 'J_arm_l_04', 'J_arm_l_05', 'J_arm_l_06', 'J_arm_l_07',
        'J_arm_r_01', 'J_arm_r_02', 'J_arm_r_03', 'J_arm_r_04', 'J_arm_r_05', 'J_arm_r_06', 'J_arm_r_07',
        'J_head_yaw', 'J_head_pitch',
        'J_waist_pitch', 'J_waist_roll', 'J_waist_yaw',
        'J_hip_l_roll', 'J_hip_l_yaw', 'J_hip_l_pitch', 'J_knee_l_pitch', 'J_ankle_l_pitch', 'J_ankle_l_roll',
        'J_hip_r_roll', 'J_hip_r_yaw', 'J_hip_r_pitch', 'J_knee_r_pitch', 'J_ankle_r_pitch', 'J_ankle_r_roll',
        # 'J_hip_r_roll', 'J_hip_r_yaw', 'J_hip_r_pitch', 'J_knee_r_pitch', 'J_r_ankle_pitch', 'J_r_ankle_roll',
        # 'J_hip_l_roll', 'J_hip_l_yaw', 'J_hip_l_pitch', 'J_knee_l_pitch', 'J_l_ankle_pitch', 'J_l_ankle_roll',
    ],
    DOF_NAMES_STD={
        'J_head_yaw': 'head_yaw',
        'J_head_pitch': 'head_pitch',
        'J_arm_r_01': 'right_shoulder_pitch',
        'J_arm_r_02': 'right_shoulder_roll',
        'J_arm_r_03': 'right_shoulder_yaw',
        'J_arm_r_04': 'right_elbow_pitch',
        'J_arm_r_05': 'right_wrist_yaw',
        'J_arm_r_06': 'right_wrist_pitch',
        'J_arm_r_07': 'right_wrist_roll',
        'J_arm_l_01': 'left_shoulder_pitch',
        'J_arm_l_02': 'left_shoulder_roll',
        'J_arm_l_03': 'left_shoulder_yaw',
        'J_arm_l_04': 'left_elbow_pitch',
        'J_arm_l_05': 'left_wrist_yaw',
        'J_arm_l_06': 'left_wrist_pitch',
        'J_arm_l_07': 'left_wrist_roll',
        'J_waist_pitch': 'waist_pitch',
        'J_waist_roll': 'waist_roll',
        'J_waist_yaw': 'waist_yaw',
        'J_hip_r_roll': 'right_hip_roll',
        'J_hip_r_yaw': 'right_hip_yaw',
        'J_hip_r_pitch': 'right_hip_pitch',
        'J_knee_r_pitch': 'right_knee_pitch',
        'J_ankle_r_pitch': 'right_ankle_pitch',
        'J_ankle_r_roll': 'right_ankle_roll',
        # 'J_r_ankle_pitch': 'right_ankle_pitch',
        # 'J_r_ankle_roll': 'right_ankle_roll',
        'J_hip_l_roll': 'left_hip_roll',
        'J_hip_l_yaw': 'left_hip_yaw',
        'J_hip_l_pitch': 'left_hip_pitch',
        'J_knee_l_pitch': 'left_knee_pitch',
        'J_ankle_l_pitch': 'left_ankle_pitch',
        'J_ankle_l_roll': 'left_ankle_roll',
        # 'J_l_ankle_pitch': 'left_ankle_pitch',
        # 'J_l_ankle_roll': 'left_ankle_roll',
    },
    URDF='loong/AzureLoong_1_proc.urdf',
    # URDF='Loong/AzureLoong.urdf',
    KP=[
        200,120,80,60,40,20,10,
        200,120,80,60,40,20,10,

        # 1000,1000,6000,6000,6000,
        # 100,100,6000,6000,6000,
        3,3,6000,6000,6000,

        # 100,100,600,600,600,
        # 200,100,200,200,100,100,
        # 200,100,200,200,100,100,

        # 200,200,400,200,100,100,
        # 200,200,400,200,100,100,

        500,250,700,700,100,100,
        500,250,700,700,100,100,

        # 400,200,400,400,120,120,
        # 400,200,400,400,120,120,
    ],
    KD=[
        20,12,8,6,4,2,1,
        20,12,8,6,4,2,1,
        # 30,30,40,40,40,
        0.5,0.5,40,40,40,

        # 25,20,25,25,10,10,
        # 25,20,25,25,10,10
        # 10, 10, 10, 10, 0.5, 0.5,
        # 10, 10, 10, 10, 0.5, 0.5,
        # 1, 1, 2, 2, 1, 1,
        # 1, 1, 2, 2, 1, 1,

        # 2, 2, 2, 4, 0.5, 0.5,
        # 2, 2, 2, 4, 0.5, 0.5,

        25, 9, 17, 13, 2.5, 1.5,
        25, 9, 17, 13, 2.5, 1.5,
    ],
    Q_RESET={
        'J_arm_r_02': -1.4,
        'J_arm_r_03': -1.6,
        'J_arm_l_02': 1.4,
        'J_arm_l_03': 1.6,
        'J_hip_r_pitch': 0.305913,
        'J_knee_r_pitch': -0.670418,
        'J_ankle_r_pitch': 0.371265,
        'J_hip_l_pitch': 0.305913,
        'J_knee_l_pitch': -0.670418,
        'J_ankle_l_pitch': 0.371265,
    }
)

a2b = dict(
    NAME='a2b',
    DOF_NAMES_STD={
        'idx01_left_hip_roll': 'left_hip_roll',
        'idx02_left_hip_yaw': 'left_hip_yaw',
        'idx03_left_hip_pitch': 'left_hip_pitch',
        'idx04_left_tarsus': 'left_knee_pitch',
        'idx05_left_toe_pitch': 'left_ankle_pitch',
        'idx06_left_toe_roll': 'left_ankle_roll',
        'idx07_right_hip_roll': 'right_hip_roll',
        'idx08_right_hip_yaw': 'right_hip_yaw',
        'idx09_right_hip_pitch': 'right_hip_pitch',
        'idx10_right_tarsus': 'right_knee_pitch',
        'idx11_right_toe_pitch': 'right_ankle_pitch',
        'idx12_right_toe_roll': 'right_ankle_roll',
        'idx13_left_arm_joint1': 'left_shoulder_pitch',
        'idx14_left_arm_joint2': 'left_shoulder_roll',
        'idx15_left_arm_joint3': 'left_shoulder_yaw',
        'idx16_left_arm_joint4': 'left_elbow_pitch',
        'idx17_left_arm_joint5': 'left_wrist_yaw',
        'idx18_left_arm_joint6': 'left_wrist_pitch',
        'idx19_left_arm_joint7': 'left_wrist_roll',
        'idx20_right_arm_joint1': 'right_shoulder_pitch',
        'idx21_right_arm_joint2': 'right_shoulder_roll',
        'idx22_right_arm_joint3': 'right_shoulder_yaw',
        'idx23_right_arm_joint4': 'right_elbow_pitch',
        'idx24_right_arm_joint5': 'right_wrist_yaw',
        'idx25_right_arm_joint6': 'right_wrist_pitch',
        'idx26_right_arm_joint7': 'right_wrist_roll',
    },
    # URDF='a2/raise_a2_t2d0_basic/model.urdf',
    URDF='a2/raise_a2_t2d0_flagship/model.urdf',
    # KP=[
    # ],
    # KD=[
    # ],
)


dobot = {
    'NAME': 'dobot',
    'URDF': 'dobot/urdf/dobot_simplified_hand.urdf',
    'DOF_NAMES_STD': {
        'leg_l1_joint': 'left_hip_pitch',
        'leg_l2_joint': 'left_hip_roll',
        'leg_l3_joint': 'left_hip_yaw',
        'leg_l4_joint': 'left_knee_pitch',
        'leg_l5_joint': 'left_ankle_pitch',
        'leg_l6_joint': 'left_ankle_roll',
        'leg_r1_joint': 'right_hip_pitch',
        'leg_r2_joint': 'right_hip_roll',
        'leg_r3_joint': 'right_hip_yaw',
        'leg_r4_joint': 'right_knee_pitch',
        'leg_r5_joint': 'right_ankle_pitch',
        'leg_r6_joint': 'right_ankle_roll',
    },
    'KP': {
        # Left leg
        'leg_l1_joint': 230.0,
        'leg_l2_joint': 230.0,
        'leg_l3_joint': 120.0,
        'leg_l4_joint': 370.0,
        'leg_l5_joint': 75.0,
        'leg_l6_joint': 75.0,
        # Right leg
        'leg_r1_joint': 230.0,
        'leg_r2_joint': 230.0,
        'leg_r3_joint': 120.0,
        'leg_r4_joint': 370.0,
        'leg_r5_joint': 75.0,
        'leg_r6_joint': 75.0,
    },
    'KD': {
        # Left leg
        'leg_l1_joint': 3.0,
        'leg_l2_joint': 3.0,
        'leg_l3_joint': 1.65,
        'leg_l4_joint': 5.0,
        'leg_l5_joint': 1.0,
        'leg_l6_joint': 1.0,
        # Right leg
        'leg_r1_joint': 3.0,
        'leg_r2_joint': 3.0,
        'leg_r3_joint': 1.65,
        'leg_r4_joint': 5.0,
        'leg_r5_joint': 1.0,
        'leg_r6_joint': 1.0,
    },
}

atom = {
    'NAME': 'atom',
    'URDF': 'atom/urdf/atom.urdf',
    'DOF_NAMES_STD': {
        'leg_l1_joint': 'left_hip_pitch',
        'leg_l2_joint': 'left_hip_roll',
        'leg_l3_joint': 'left_hip_yaw',
        'leg_l4_joint': 'left_knee_pitch',
        'leg_l5_joint': 'left_ankle_pitch',
        'leg_l6_joint': 'left_ankle_roll',
        'leg_r1_joint': 'right_hip_pitch',
        'leg_r2_joint': 'right_hip_roll',
        'leg_r3_joint': 'right_hip_yaw',
        'leg_r4_joint': 'right_knee_pitch',
        'leg_r5_joint': 'right_ankle_pitch',
        'leg_r6_joint': 'right_ankle_roll',
        'uidx_l_arm_joint1': 'left_shoulder_pitch',
        'uidx_l_arm_joint2': 'left_elbow_pitch',
        'uidx_r_arm_joint1': 'right_shoulder_pitch',
        'uidx_r_arm_joint2': 'right_elbow_pitch',
    },
    'KP': {
        # Left leg
        'leg_l1_joint': 230.0,
        'leg_l2_joint': 230.0,
        'leg_l3_joint': 120.0,
        'leg_l4_joint': 370.0,
        'leg_l5_joint': 75.0,
        'leg_l6_joint': 75.0,
        # Right leg
        'leg_r1_joint': 230.0,
        'leg_r2_joint': 230.0,
        'leg_r3_joint': 120.0,
        'leg_r4_joint': 370.0,
        'leg_r5_joint': 75.0,
        'leg_r6_joint': 75.0,
        'uidx_l_arm_joint1': 30,
        'uidx_l_arm_joint2': 30,
        'uidx_r_arm_joint1': 30,
        'uidx_r_arm_joint2': 30,
    },
    'KD': {
        # Left leg
        'leg_l1_joint': 3.0,
        'leg_l2_joint': 3.0,
        'leg_l3_joint': 1.65,
        'leg_l4_joint': 5.0,
        'leg_l5_joint': 1.0,
        'leg_l6_joint': 1.0,
        # Right leg
        'leg_r1_joint': 3.0,
        'leg_r2_joint': 3.0,
        'leg_r3_joint': 1.65,
        'leg_r4_joint': 5.0,
        'leg_r5_joint': 1.0,
        'leg_r6_joint': 1.0,
        'uidx_l_arm_joint1': 1.,
        'uidx_l_arm_joint2': 1.,
        'uidx_r_arm_joint1': 1.,
        'uidx_r_arm_joint2': 1.,
    },
    'Q_RESET': {
        # Left leg
        'leg_l1_joint': -0.25,  #  left_hip_pitch_joint
        'leg_l2_joint': 0.0,  #  left_hip_roll_joint
        'leg_l3_joint': 0.0,  #  left_hip_yaw_joint
        'leg_l4_joint': 0.5,  #  left_knee_joint
        'leg_l5_joint': -0.15,  #  left_ankle_pitch_joint
        'leg_l6_joint': 0.0,  #  left_ankle_roll_joint
        # Right leg
        'leg_r1_joint': -0.25,  #  right_hip_pitch_joint
        'leg_r2_joint': 0.0,  #  right_hip_roll_joint
        'leg_r3_joint': 0.0,  #  right_hip_yaw_joint
        'leg_r4_joint': 0.5,  #  right_knee_joint
        'leg_r5_joint': -0.15,  #  right_ankle_pitch_joint
        'leg_r6_joint': 0.0,  #  right_ankle_roll_joint

        'uidx_l_arm_joint2': 1.57,
        'uidx_r_arm_joint2': 1.57,
    },
    'TAU_LIMIT': [
        280.0, 308.0, 140.0, 360.0, 130.0, 130.0,
        280.0, 308.0, 140.0, 360.0, 130.0, 130.0,
        36.0, 36.0,
    ],
}

adam_sp = {
    'NAME': 'adam_sp',
    # 'URDF': 'pnd_models/adam_sp/adam_sp_1.urdf',
    'URDF': 'pnd_models/adam_sp/adam_sp_2.urdf',
    'DOF_NAMES': [
        'hipPitch_Left',
        'hipRoll_Left',
        'hipYaw_Left',
        'kneePitch_Left',
        'anklePitch_Left',
        'ankleRoll_Left',
        'hipPitch_Right',
        'hipRoll_Right',
        'hipYaw_Right',
        'kneePitch_Right',
        'anklePitch_Right',
        'ankleRoll_Right',
        'waistRoll',
        'waistPitch',
        'waistYaw',
        'shoulderPitch_Left',
        'shoulderRoll_Left',
        'shoulderYaw_Left',
        'elbow_Left',
        'wristYaw_Left',
        'wristPitch_Left',
        'wristRoll_Left',
        'shoulderPitch_Right',
        'shoulderRoll_Right',
        'shoulderYaw_Right',
        'elbow_Right',
        'wristYaw_Right',
        'wristPitch_Right',
        'wristRoll_Right',
    ],
    'DOF_NAMES_STD': {
        'hipPitch_Left': 'left_hip_pitch',
        'hipRoll_Left': 'left_hip_roll',
        'hipYaw_Left': 'left_hip_yaw',
        'kneePitch_Left': 'left_knee_pitch',
        'anklePitch_Left': 'left_ankle_pitch',
        'ankleRoll_Left': 'left_ankle_roll',
        'hipPitch_Right': 'right_hip_pitch',
        'hipRoll_Right': 'right_hip_roll',
        'hipYaw_Right': 'right_hip_yaw',
        'kneePitch_Right': 'right_knee_pitch',
        'anklePitch_Right': 'right_ankle_pitch',
        'ankleRoll_Right': 'right_ankle_roll',
        'waistRoll': 'waist_roll',
        'waistPitch': 'waist_pitch',
        'waistYaw': 'waist_yaw',
        'shoulderPitch_Left': 'left_shoulder_pitch',
        'shoulderRoll_Left': 'left_shoulder_roll',
        'shoulderYaw_Left': 'left_shoulder_yaw',
        'elbow_Left': 'left_elbow_pitch',
        'wristYaw_Left': 'left_wrist_yaw',
        'wristPitch_Left': 'left_wrist_pitch',
        'wristRoll_Left': 'left_wrist_roll',
        'shoulderPitch_Right': 'right_shoulder_pitch',
        'shoulderRoll_Right': 'right_shoulder_roll',
        'shoulderYaw_Right': 'right_shoulder_yaw',
        'elbow_Right': 'right_elbow_pitch',
        'wristYaw_Right': 'right_wrist_yaw',
        'wristPitch_Right': 'right_wrist_pitch',
        'wristRoll_Right': 'right_wrist_roll',
    },
    'KP': [
        305.0, 700.0, 405.0, 305.0, 20.0, 10.0,
        305.0, 700.0, 405.0, 305.0, 20.0, 10.0,
        # 305.0, 700.0, 405.0, 305.0, 30.0, 0.0,
        # 305.0, 700.0, 405.0, 305.0, 30.0, 0.0,
        405.0, 405.0, 205.0,
        # 18.0, 9.0, 9.0, 9.0, 7.0, 7.0, 7.0,
        # 18.0, 9.0, 9.0, 9.0, 7.0, 7.0, 7.0,
        18.0, 18.0, 18.0, 9.0, 7.0, 7.0, 7.0,
        18.0, 18.0, 18.0, 9.0, 7.0, 7.0, 7.0,
    ],
    'KD': [
        6.1, 30.0, 6.1, 6.1, 1.25, 1.0,
        6.1, 30.0, 6.1, 6.1, 1.25, 1.0,
        # 6.1, 30.0, 6.1, 6.1, 2.25, 0.25,
        # 6.1, 30.0, 6.1, 6.1, 2.25, 0.25,
        6.1, 6.1, 4.1,
        # 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5,
        # 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5,
        2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0,
        2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0,
    ],
    'ASSET_OPTIONS': {
        'flip_visual_attachments': True,
    },
    'MOTOR_IPS': [
        '10.10.10.90',
        '10.10.10.91',
        '10.10.10.92',
        '10.10.10.50',
        '10.10.10.51',
        '10.10.10.52',
        '10.10.10.53',
        '10.10.10.54',
        '10.10.10.55',
        '10.10.10.70',
        '10.10.10.71',
        '10.10.10.72',
        '10.10.10.73',
        '10.10.10.74',
        '10.10.10.75',
        '10.10.10.10',
        '10.10.10.11',
        '10.10.10.12',
        '10.10.10.13',
        '10.10.10.14',
        '10.10.10.15',
        '10.10.10.16',
        '10.10.10.30',
        '10.10.10.31',
        '10.10.10.32',
        '10.10.10.33',
        '10.10.10.34',
        '10.10.10.35',
        '10.10.10.36',
    ],
    'Q_RESET': {
        'hipPitch_Left' : -0.3 ,
        'hipRoll_Left' : -0.0 ,
        'hipYaw_Left' : -0.2 ,
        'kneePitch_Left' : 0.6,
        'anklePitch_Left' : -0.3 ,
        'ankleRoll_Left' : -0 ,
        'hipPitch_Right' : -0.3 ,
        'hipRoll_Right' : 0.0 ,
        'hipYaw_Right' : 0.2 ,
        'kneePitch_Right' : 0.6,
        'anklePitch_Right' : -0.3 ,
        'ankleRoll_Right' : -0 ,
        'waistRoll' : 0. ,
        'waistPitch' : 0. ,
        'waistYaw' : 0. ,
        'shoulderPitch_Left' : 0. ,
        'shoulderRoll_Left' : 0.2 ,
        'shoulderYaw_Left' : 0. ,
        'elbow_Left' : 0. ,
        'wristYaw_Left' : 0. ,
        'shoulderPitch_Right' : 0. ,
        'shoulderRoll_Right' : -0.2 ,
        'shoulderYaw_Right' : 0. ,
        'elbow_Right' : 0. ,
        'wristYaw_Right' : 0. ,
    },
    'TAU_LIMIT': {
        'hipPitch': 160,
        'hipRoll': 160,
        'hipYaw': 90,
        'kneePitch': 160,
        'waist': 100,
        # 'ankle': 6,
        'ankle': 40,
    },
}

adam2 = {
    'NAME': 'adam',
    'URDF': 'adam/adam_lite/urdf/adam_lite_1_1.urdf',
    'MJCF': 'adam/adam_lite_mj/sence_1.xml',
    'DOF_NAMES': [
        'hipPitch_Left',
        'hipRoll_Left',
        'hipYaw_Left',
        'kneePitch_Left',
        'anklePitch_Left',
        'ankleRoll_Left',
        'hipPitch_Right',
        'hipRoll_Right',
        'hipYaw_Right',
        'kneePitch_Right',
        'anklePitch_Right',
        'ankleRoll_Right',
        'waistRoll',
        'waistPitch',
        'waistYaw',
        'shoulderPitch_Left',
        'shoulderRoll_Left',
        'shoulderYaw_Left',
        'elbow_Left',
        # 'wristYaw_Left',
        'shoulderPitch_Right',
        'shoulderRoll_Right',
        'shoulderYaw_Right',
        'elbow_Right',
        # 'wristYaw_Right',
    ],
    'DOF_NAMES_STD': {
        'hipPitch_Left': 'left_hip_pitch',
        'hipRoll_Left': 'left_hip_roll',
        'hipYaw_Left': 'left_hip_yaw',
        'kneePitch_Left': 'left_knee_pitch',
        'anklePitch_Left': 'left_ankle_pitch',
        'ankleRoll_Left': 'left_ankle_roll',
        'hipPitch_Right': 'right_hip_pitch',
        'hipRoll_Right': 'right_hip_roll',
        'hipYaw_Right': 'right_hip_yaw',
        'kneePitch_Right': 'right_knee_pitch',
        'anklePitch_Right': 'right_ankle_pitch',
        'ankleRoll_Right': 'right_ankle_roll',
        'waistRoll': 'waist_roll',
        'waistPitch': 'waist_pitch',
        'waistYaw': 'waist_yaw',
        'shoulderPitch_Left': 'left_shoulder_pitch',
        'shoulderRoll_Left': 'left_shoulder_roll',
        'shoulderYaw_Left': 'left_shoulder_yaw',
        'elbow_Left': 'left_elbow_pitch',
        'wristYaw_Left': 'left_wrist_yaw',
        'shoulderPitch_Right': 'right_shoulder_pitch',
        'shoulderRoll_Right': 'right_shoulder_roll',
        'shoulderYaw_Right': 'right_shoulder_yaw',
        'elbow_Right': 'right_elbow_pitch',
        'wristYaw_Right': 'right_wrist_yaw',
    },
    'KP': [
        305.0, 700.0, 405.0, 305.0, 20.0, 10.0,
        305.0, 700.0, 405.0, 305.0, 20.0, 10.0,
        # 305.0, 700.0, 405.0, 305.0, 30.0, 0.0,
        # 305.0, 700.0, 405.0, 305.0, 30.0, 0.0,
        405.0, 405.0, 205.0,
        18.0, 9.0, 9.0, 9.0,
        18.0, 9.0, 9.0, 9.0,
    ],
    'KD': [
        6.1, 30.0, 6.1, 6.1, 1.25, 1.0,
        6.1, 30.0, 6.1, 6.1, 1.25, 1.0,
        # 6.1, 30.0, 6.1, 6.1, 2.25, 0.25,
        # 6.1, 30.0, 6.1, 6.1, 2.25, 0.25,
        6.1, 6.1, 4.1,
        1.0, 1.0, 1.0, 1.0,
        1.0, 1.0, 1.0, 1.0,
    ],
    'ASSET_OPTIONS': {
        'flip_visual_attachments': True,
    },
    'MOTOR_IPS': [
        '10.10.10.90',
        '10.10.10.91',
        '10.10.10.92',
        '10.10.10.50',
        '10.10.10.51',
        '10.10.10.52',
        '10.10.10.53',
        '10.10.10.54',
        '10.10.10.55',
        '10.10.10.70',
        '10.10.10.71',
        '10.10.10.72',
        '10.10.10.73',
        '10.10.10.74',
        '10.10.10.75',
        '10.10.10.10',
        '10.10.10.11',
        '10.10.10.12',
        '10.10.10.13',
        # '10.10.10.14',
        '10.10.10.30',
        '10.10.10.31',
        '10.10.10.32',
        '10.10.10.33',
        # '10.10.10.34',
    ],
    'Q_RESET': {
        'hipPitch_Left' : -0.3 ,
        'hipRoll_Left' : -0.0 ,
        'hipYaw_Left' : -0.2 ,
        'kneePitch_Left' : 0.6,
        'anklePitch_Left' : -0.3 ,
        'ankleRoll_Left' : -0 ,
        'hipPitch_Right' : -0.3 ,
        'hipRoll_Right' : 0.0 ,
        'hipYaw_Right' : 0.2 ,
        'kneePitch_Right' : 0.6,
        'anklePitch_Right' : -0.3 ,
        'ankleRoll_Right' : -0 ,
        'waistRoll' : 0. ,
        'waistPitch' : 0. ,
        'waistYaw' : 0. ,
        'shoulderPitch_Left' : 0. ,
        'shoulderRoll_Left' : 0.2 ,
        'shoulderYaw_Left' : 0. ,
        'elbow_Left' : 0. ,
        'wristYaw_Left' : 0. ,
        'shoulderPitch_Right' : 0. ,
        'shoulderRoll_Right' : -0.2 ,
        'shoulderYaw_Right' : 0. ,
        'elbow_Right' : 0. ,
        'wristYaw_Right' : 0. ,
    },
    'TAU_LIMIT': {
        'hipPitch': 160,
        'hipRoll': 160,
        'hipYaw': 90,
        'kneePitch': 160,
        'waist': 100,
        # 'ankle': 6,
        'ankle': 40,
    },
}


smpl = {
    'NAME': 'smpl',
    'MJCF': 'smpl/mjcf/smpl_humanoid.xml',
    'DOF_NAMES_STD': {
        'L_Hip_x': 'left_hip_roll',
        'L_Hip_y': 'left_hip_pitch',
        'L_Hip_z': 'left_hip_yaw',
        'L_Knee_y': 'left_knee_pitch',
        'L_Ankle_x': 'left_ankle_roll',
        'L_Ankle_y': 'left_ankle_pitch',
        'R_Hip_x': 'right_hip_roll',
        'R_Hip_y': 'right_hip_pitch',
        'R_Hip_z': 'right_hip_yaw',
        'R_Knee_y': 'right_knee_pitch',
        'R_Ankle_x': 'right_ankle_roll',
        'R_Ankle_y': 'right_ankle_pitch',
        'Torso_x': 'waist_roll',
        'Torso_y': 'waist_pitch',
        'Torso_z': 'waist_yaw',
        'Neck_x': 'head_roll',
        'Neck_y': 'head_pitch',
        'Neck_z': 'head_yaw',
        'L_Shoulder_x': 'left_shoulder_roll',
        'L_Shoulder_y': 'left_shoulder_pitch',
        'L_Shoulder_z': 'left_shoulder_yaw',
        'L_Elbow_y': 'left_elbow_pitch',
        'L_Wrist_x': 'left_wrist_roll',
        'L_Wrist_y': 'left_wrist_pitch',
        'L_Wrist_z': 'left_wrist_yaw',
        'R_Shoulder_x': 'right_shoulder_roll',
        'R_Shoulder_y': 'right_shoulder_pitch',
        'R_Shoulder_z': 'right_shoulder_yaw',
        'R_Elbow_y': 'right_elbow_pitch',
        'R_Wrist_x': 'right_wrist_roll',
        'R_Wrist_y': 'right_wrist_pitch',
        'R_Wrist_z': 'right_wrist_yaw',
    },
    'KP': {
        "L_Hip_": 800,
        "R_Hip_": 800,
        "L_Knee_": 800,
        "R_Knee_": 800,
        "L_Ankle_": 800,
        "R_Ankle_": 800,
        "L_Toe_": 500,
        "R_Toe_": 500,

        "Torso_": 1000,
        "Spine_": 1000,
        "Chest_": 1000,
        "Neck_": 500,
        "Head_": 500,
        "L_Thorax_": 500,
        "R_Thorax_": 500,

        "L_Shoulder_": 500,
        "R_Shoulder_": 500,
        "L_Elbow_": 500,
        "R_Elbow_": 500,
        "L_Wrist_": 300,
        "R_Wrist_": 300,
        "L_Hand_": 300,
        "R_Hand_": 300,
    },
    'KD': {
        "L_Hip_": 80,
        "R_Hip_": 80,
        "L_Knee_": 80,
        "R_Knee_": 80,
        "L_Ankle_": 80,
        "R_Ankle_": 80,
        "L_Toe_": 50,
        "R_Toe_": 50,

        "Torso_": 100,
        "Spine_": 100,
        "Chest_": 100,
        "Neck_": 50,
        "Head_": 50,
        "L_Thorax_": 50,
        "R_Thorax_": 50,

        "L_Shoulder_": 50,
        "R_Shoulder_": 50,
        "L_Elbow_": 50,
        "R_Elbow_": 50,
        "L_Wrist_": 30,
        "R_Wrist_": 30,
    },
}


star1 = {
    'NAME': 'star1',
    'URDF': 'star1/urdf/l3_modify_1.urdf',
    # 'URDF': 'star1/urdf/l3_with_hand_fixedpin_xml.urdf',
    'DOF_NAMES_STD': {
        'left_shoulder_pitch_joint': 'left_shoulder_pitch',
        'left_shoulder_roll_joint': 'left_shoulder_roll',
        'left_arm_yaw_joint': 'left_shoulder_yaw',
        'left_elbow_pitch_joint': 'left_elbow_pitch',
        'left_elbow_yaw_joint': 'left_wrist_yaw',
        'left_wrist_pitch_joint': 'left_wrist_pitch',
        'left_wrist_roll_joint': 'left_wrist_roll',
        'neck_yaw_joint': 'head_yaw',
        'neck_pitch_joint': 'head_pitch',
        'right_shoulder_pitch_joint': 'right_shoulder_pitch',
        'right_shoulder_roll_joint': 'right_shoulder_roll',
        'right_arm_yaw_joint': 'right_shoulder_yaw',
        'right_elbow_pitch_joint': 'right_elbow_pitch',
        'right_elbow_yaw_joint': 'right_wrist_yaw',
        'right_wrist_pitch_joint': 'right_wrist_pitch',
        'right_wrist_roll_joint': 'right_wrist_roll',
        'waist_pitch_joint': 'waist_pitch',
        'waist_roll_joint': 'waist_roll',
        'waist_yaw_joint': 'waist_yaw',
        'left_hip_roll_joint': 'left_hip_roll',
        'left_hip_yaw_joint': 'left_hip_yaw',
        'left_hip_pitch_joint': 'left_hip_pitch',
        'left_knee_joint': 'left_knee',
        'left_ankle_pitch_joint': 'left_ankle_pitch',
        'left_ankle_roll_joint': 'left_ankle_roll',
        'right_hip_roll_joint': 'right_hip_roll',
        'right_hip_yaw_joint': 'right_hip_yaw',
        'right_hip_pitch_joint': 'right_hip_pitch',
        'right_knee_joint': 'right_knee',
        'right_ankle_pitch_joint': 'right_ankle_pitch',
        'right_ankle_roll_joint': 'right_ankle_roll',
    },
    'KP': {
        'left_shoulder_pitch_joint' :  50 ,
        'left_shoulder_roll_joint' :  50 ,
        'left_arm_yaw_joint' :  50 ,
        'left_elbow_pitch_joint' :  50 ,
        'left_elbow_yaw_joint' :  20 ,
        'left_wrist_pitch_joint' :  20 ,
        'left_wrist_roll_joint' :  20 ,
        'neck_yaw_joint' :  40 ,
        'neck_pitch_joint' :  40 ,
        'right_shoulder_pitch_joint' :  50 ,
        'right_shoulder_roll_joint' :  50 ,
        'right_arm_yaw_joint' :  50 ,
        'right_elbow_pitch_joint' :  50 ,
        'right_elbow_yaw_joint' :  20 ,
        'right_wrist_pitch_joint' :  20 ,
        'right_wrist_roll_joint' :  20 ,
        'waist_pitch_joint' :  100 ,
        'waist_roll_joint' :  200 ,
        'waist_yaw_joint' :  100 ,
        'left_hip_roll_joint' :  200 ,
        'left_hip_yaw_joint' :  100 ,
        'left_hip_pitch_joint' :  300 ,
        'left_knee_joint' :  300 ,
        'left_ankle_pitch_joint' :  100 ,
        'left_ankle_roll_joint' :  100 ,
        'right_hip_roll_joint' :  200 ,
        'right_hip_yaw_joint' :  100 ,
        'right_hip_pitch_joint' :  300 ,
        'right_knee_joint' :  300 ,
        'right_ankle_pitch_joint' :  100 ,
        'right_ankle_roll_joint' :  100 ,
    },
    'KD': {
        'left_shoulder_pitch_joint' :  2 ,
        'left_shoulder_roll_joint' :  2 ,
        'left_arm_yaw_joint' : 2 ,
        'left_elbow_pitch_joint' :  2 ,
        'left_elbow_yaw_joint' :  0.5 ,
        'left_wrist_pitch_joint' :  0.5 ,
        'left_wrist_roll_joint' :  0.5 ,
        'neck_yaw_joint' :  1 ,
        'neck_pitch_joint' :  1 ,
        'right_shoulder_pitch_joint' :  2 ,
        'right_shoulder_roll_joint' :  2 ,
        'right_arm_yaw_joint' :  2,
        'right_elbow_pitch_joint' :  2 ,
        'right_elbow_yaw_joint' :  0.5 ,
        'right_wrist_pitch_joint' :  0.5 ,
        'right_wrist_roll_joint' :  0.5 ,
        'waist_pitch_joint' : 5 ,
        'waist_roll_joint' :  5 ,
        'waist_yaw_joint' :  3 ,
        'left_hip_roll_joint' :  4 ,
        'left_hip_yaw_joint' :  2 ,
        'left_hip_pitch_joint' :  5,
        'left_knee_joint' :  5,
        'left_ankle_pitch_joint' :  4,
        'left_ankle_roll_joint' :  4,
        'right_hip_roll_joint' :  4,
        'right_hip_yaw_joint' :  2,
        'right_hip_pitch_joint' :  5,
        'right_knee_joint' :  5,
        'right_ankle_pitch_joint' :  4 ,
        'right_ankle_roll_joint' :  4 ,
    },
}


h1_2 = {
    'NAME': 'h1_2',
    'URDF': 'h1_2/h1_2_simplified.urdf',
    'DOF_NAMES': [
        'left_hip_yaw_joint',
        'left_hip_pitch_joint',
        'left_hip_roll_joint',
        'left_knee_joint',
        'left_ankle_pitch_joint',
        'left_ankle_roll_joint',
        'right_hip_yaw_joint',
        'right_hip_pitch_joint',
        'right_hip_roll_joint',
        'right_knee_joint',
        'right_ankle_pitch_joint',
        'right_ankle_roll_joint',
        'torso_joint',
        'left_shoulder_pitch_joint',
        'left_shoulder_roll_joint',
        'left_shoulder_yaw_joint',
        'left_elbow_pitch_joint',
        'left_elbow_roll_joint',
        'left_wrist_pitch_joint',
        'left_wrist_yaw_joint',
        'right_shoulder_pitch_joint',
        'right_shoulder_roll_joint',
        'right_shoulder_yaw_joint',
        'right_elbow_pitch_joint',
        'right_elbow_roll_joint',
        'right_wrist_pitch_joint',
        'right_wrist_yaw_joint',
    ],
    'DOF_NAMES_STD': {
        'left_hip_yaw_joint': 'left_hip_yaw',
        'left_hip_roll_joint': 'left_hip_roll',
        'left_hip_pitch_joint': 'left_hip_pitch',
        'left_knee_joint': 'left_knee_pitch',
        'left_ankle_pitch_joint': 'left_ankle_pitch',
        'left_ankle_roll_joint': 'left_ankle_roll',
        'right_hip_yaw_joint': 'right_hip_yaw',
        'right_hip_roll_joint': 'right_hip_roll',
        'right_hip_pitch_joint': 'right_hip_pitch',
        'right_knee_joint': 'right_knee_pitch',
        'right_ankle_pitch_joint': 'right_ankle_pitch',
        'right_ankle_roll_joint': 'right_ankle_roll',
        'torso_joint': 'waist_yaw',
        'left_shoulder_pitch_joint': 'left_shoulder_pitch',
        'left_shoulder_roll_joint': 'left_shoulder_roll',
        'left_shoulder_yaw_joint': 'left_shoulder_yaw',
        'left_elbow_pitch_joint': 'left_elbow_pitch',
        'left_elbow_roll_joint': 'left_elbow_yaw',
        'left_wrist_pitch_joint': 'left_wrist_pitch',
        'left_wrist_yaw_joint': 'left_wrist_roll',
        'right_shoulder_pitch_joint': 'right_shoulder_pitch',
        'right_shoulder_roll_joint': 'right_shoulder_roll',
        'right_shoulder_yaw_joint': 'right_shoulder_yaw',
        'right_elbow_pitch_joint': 'right_elbow_pitch',
        'right_elbow_roll_joint': 'right_elbow_yaw',
        'right_wrist_pitch_joint': 'right_wrist_pitch',
        'right_wrist_yaw_joint': 'right_wrist_roll',
    },
    'KP': {
        'hip_yaw': 200,
        'hip_roll': 200,
        'hip_pitch': 200,
        'knee': 300,
        'ankle': 40,
        'torso': 300,
        'shoulder': 100,
        "elbow": 100,
    },
    'KD': {
        'hip_yaw': 5,
        'hip_roll': 5,
        'hip_pitch': 5,
        'knee': 6,
        # 'hip_yaw': 2.5,
        # 'hip_roll': 2.5,
        # 'hip_pitch': 2.5,
        # 'knee': 4.,
        'ankle': 2,
        'torso': 6,
        'shoulder': 2,
        "elbow": 2,
    },
    'Q_RESET': { # = target angles [rad] when action = 0.0
       'left_hip_yaw_joint' : 0.00,
       'left_hip_roll_joint' : 0.02,
       'left_hip_pitch_joint' : -0.4,
       'left_knee_joint' : 0.8,
       'left_ankle_pitch_joint' : -0.4,
       'right_hip_yaw_joint' : -0.00,
       'right_hip_roll_joint' : -0.02,
       'right_hip_pitch_joint' : -0.4,
       'right_knee_joint' : 0.8,
       'right_ankle_pitch_joint' : -0.4,
       'torso_joint' : 0.,
       'left_shoulder_pitch_joint' : 0.,
    #    'left_shoulder_roll_joint' : 0,
       'left_shoulder_roll_joint' : 0.2,
       'left_shoulder_yaw_joint' : 0.,
    #    'left_elbow_joint'  : 0.,
       'left_elbow_pitch_joint'  : 1.57,
       'right_shoulder_pitch_joint' : 0.,
    #    'right_shoulder_roll_joint' : 0.0,
       'right_shoulder_roll_joint' : -0.2,
       'right_shoulder_yaw_joint' : 0.,
    #    'right_elbow_joint' : 0.,
       'right_elbow_pitch_joint' : 1.57,
    },
}


aliengo = dict(
    NAME='aliengo',
    NUM_DOFS=12,
    KP=[35.] * 12,
    KD=[1.] * 12,
    DOF_NAMES = [
        'FR_hip_joint', 'FR_thigh_joint', 'FR_calf_joint',
        'FL_hip_joint', 'FL_thigh_joint', 'FL_calf_joint',
        'RR_hip_joint', 'RR_thigh_joint', 'RR_calf_joint',
        'RL_hip_joint', 'RL_thigh_joint', 'RL_calf_joint',
    ],
    DOF_NAMES_STD = {
        'FL_hip_joint': 'left_shoulder_yaw',
        'RL_hip_joint': 'left_hip_yaw',
        'FR_hip_joint': 'right_shoulder_yaw',
        'RR_hip_joint': 'right_hip_yaw',
        'FL_thigh_joint': 'left_shoulder_pitch',
        'RL_thigh_joint': 'left_hip_pitch',
        'FR_thigh_joint': 'right_shoulder_pitch',
        'RR_thigh_joint': 'right_hip_pitch',
        'FL_calf_joint': 'left_elbow_pitch',
        'RL_calf_joint': 'left_knee_pitch',
        'FR_calf_joint': 'right_elbow_pitch',
        'RR_calf_joint': 'right_knee_pitch',
    },
    Q_RESET = [
        0, 0.8, -1.5, 0, 0.8, -1.5,
        0, 1.0, -1.5, 0, 1.0, -1.5,
    ],
    Q_BOOT = [
        0, 1.1, -2.7, 0, 1.1, -2.7,
        0, 1.1, -2.7, 0, 1.1, -2.7,
    ],
    URDF = 'aliengo_description/urdf/aliengo.urdf',
    ASSET_OPTIONS = {
        'flip_visual_attachments': True,
    },
)


grtiny = dict(
    NAME='grtiny',
    URDF='PTR1T1/urdf/PTR1T1_1.urdf',
    DOF_NAMES_STD={
        'left_hip_joint': 'left_hip_roll',
        'left_thigh_joint': 'left_hip_pitch',
        'left_shank_joint': 'left_knee_pitch',
        'left_foot_joint': 'left_ankle_pitch',
        'right_hip_joint': 'right_hip_roll',
        'right_thigh_joint': 'right_hip_pitch',
        'right_shank_joint': 'right_knee_pitch',
        'right_foot_joint': 'right_ankle_pitch',
    },
    Q_RESET={  # = target angles [rad] when action = 0.0
        'left_hip_joint': 0.0,
        'left_thigh_joint': -0.2618,
        'left_shank_joint': 0.5236,
        'left_foot_joint': -0.2618,
        'right_hip_joint': -0.,
        'right_thigh_joint': -0.2618,
        'right_shank_joint': 0.5236,
        'right_foot_joint': -0.2618,
    },
    KP={
        'thigh': 200,
        'hip': 251.625,
        'shank': 200,
        'foot': 10.9805,
    },
    KD={
        'thigh': 11,
        'hip': 14.72,
        'shank': 11,
        'foot': 0.5991,
    },
    TAU_LIMITS={
        'hip': 54,
        # 'thigh': 95, 'shank': 95,
        'thigh': 60, 'shank': 60,
        'foot': 30,
    },
)

x1 = dict(
    NAME='x1',
    URDF='x1/urdf/x1.urdf',
    DOF_NAMES_STD={
        'left_hip_pitch_joint': 'left_hip_pitch',
        'left_hip_roll_joint': 'left_hip_roll',
        'left_hip_yaw_joint': 'left_hip_yaw',
        'left_knee_pitch_joint': 'left_knee_pitch',
        'left_ankle_pitch_joint': 'left_ankle_pitch',
        'left_ankle_roll_joint': 'left_ankle_roll',
        'right_hip_pitch_joint': 'right_hip_pitch',
        'right_hip_roll_joint': 'right_hip_roll',
        'right_hip_yaw_joint': 'right_hip_yaw',
        'right_knee_pitch_joint': 'right_knee_pitch',
        'right_ankle_pitch_joint': 'right_ankle_pitch',
        'right_ankle_roll_joint': 'right_ankle_roll',
    },
    Q_RESET={  # = target angles [rad] when action = 0.0
        'left_hip_pitch_joint': 0.4,
        'left_hip_roll_joint': 0.05,
        'left_hip_yaw_joint': -0.31,
        'left_knee_pitch_joint': 0.49,
        'left_ankle_pitch_joint': -0.21,
        'left_ankle_roll_joint': 0.0,
        'right_hip_pitch_joint': -0.4,
        'right_hip_roll_joint': -0.05,
        'right_hip_yaw_joint': 0.31,
        'right_knee_pitch_joint': 0.49,
        'right_ankle_pitch_joint': -0.21,
        'right_ankle_roll_joint': 0.0,
    },
    KP={
        'hip_pitch_joint': 30, 'hip_roll_joint': 40,'hip_yaw_joint': 35,
        'knee_pitch_joint': 100, 'ankle_pitch_joint': 35, 'ankle_roll_joint': 35
    },
    KD={
        'hip_pitch_joint': 3, 'hip_roll_joint': 3.0,'hip_yaw_joint': 4,
        'knee_pitch_joint': 10, 'ankle_pitch_joint': 0.5, 'ankle_roll_joint': 0.5
    },
    TAU_LIMITS={
    },
)

x2 = dict(
    NAME='x2',
    URDF='X2T2-250910/x2_31dof_hand_1.urdf',
    DOF_NAMES=[
        'left_hip_pitch_joint', 'left_hip_roll_joint', 'left_hip_yaw_joint', 'left_knee_joint',
        'left_ankle_pitch_joint', 'left_ankle_roll_joint',
        'right_hip_pitch_joint', 'right_hip_roll_joint', 'right_hip_yaw_joint', 'right_knee_joint',
        'right_ankle_pitch_joint', 'right_ankle_roll_joint',
        'waist_yaw_joint', 'waist_pitch_joint', 'waist_roll_joint',
        'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint',
        'left_wrist_yaw_joint', 'left_wrist_pitch_joint', 'left_wrist_roll_joint',
        'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint',
        'right_wrist_yaw_joint', 'right_wrist_pitch_joint', 'right_wrist_roll_joint',
        'head_yaw_joint', 'head_pitch_joint',
    ],
    DOF_NAMES_STD={
        'left_hip_pitch_joint': 'left_hip_pitch',
        'left_hip_roll_joint': 'left_hip_roll',
        'left_hip_yaw_joint': 'left_hip_yaw',
        # 'left_knee_pitch_joint': 'left_knee_pitch',
        'left_knee_joint': 'left_knee_pitch',
        'left_ankle_pitch_joint': 'left_ankle_pitch',
        'left_ankle_roll_joint': 'left_ankle_roll',
        'right_hip_pitch_joint': 'right_hip_pitch',
        'right_hip_roll_joint': 'right_hip_roll',
        'right_hip_yaw_joint': 'right_hip_yaw',
        # 'right_knee_pitch_joint': 'right_knee_pitch',
        'right_knee_joint': 'right_knee_pitch',
        'right_ankle_pitch_joint': 'right_ankle_pitch',
        'right_ankle_roll_joint': 'right_ankle_roll',

        'waist_yaw_joint': 'waist_yaw',
        'waist_pitch_joint': 'waist_pitch',
        'waist_roll_joint': 'waist_roll',
        'left_shoulder_pitch_joint': 'left_shoulder_pitch',
        'left_shoulder_roll_joint': 'left_shoulder_roll',
        'left_shoulder_yaw_joint': 'left_shoulder_yaw',
        'left_elbow_joint': 'left_elbow_pitch',
        'left_wrist_yaw_joint': 'left_wrist_yaw',
        'left_wrist_pitch_joint': 'left_wrist_pitch',
        'left_wrist_roll_joint': 'left_wrist_roll',
        'right_shoulder_pitch_joint': 'right_shoulder_pitch',
        'right_shoulder_roll_joint': 'right_shoulder_roll',
        'right_shoulder_yaw_joint': 'right_shoulder_yaw',
        'right_elbow_joint': 'right_elbow_pitch',
        'right_wrist_yaw_joint': 'right_wrist_yaw',
        'right_wrist_pitch_joint': 'right_wrist_pitch',
        'right_wrist_roll_joint': 'right_wrist_roll',

        'head_yaw_joint': 'head_yaw',
        'head_pitch_joint': 'head_pitch',
    },
    Q_RESET={  # = target angles [rad] when action = 0.0
        'left_hip_pitch_joint': -0.2480,
        'left_hip_roll_joint': 0.,
        'left_hip_yaw_joint': 0.,
        'left_knee_joint': 0.5303,
        'left_ankle_pitch_joint': -0.2823,
        'left_ankle_roll_joint': 0.0,
        'right_hip_pitch_joint': -0.2480,
        'right_hip_roll_joint': 0.,
        'right_hip_yaw_joint': 0.,
        'right_knee_joint': 0.5303,
        'right_ankle_pitch_joint': -0.2823,
        'right_ankle_roll_joint': 0.0,

        'left_shoulder_pitch_joint': 0.4,
        'right_shoulder_pitch_joint': 0.4,
        'left_elbow_joint': -1.2,
        'right_elbow_joint': -1.2,
    },
    KP={
        'hip_pitch_joint': 120.,
        'hip_roll_joint': 120.,
        'hip_yaw_joint': 120.,
        'knee_joint': 150.,
        'ankle_pitch_joint': 40.,
        'ankle_roll_joint': 30.,

        'waist_yaw_joint': 160.,
        'waist_pitch_joint': 80.,
        'waist_roll_joint': 80.,

        '_': 40.,
    },
    KD={
        'hip_pitch_joint': 5.,
        'hip_roll_joint': 5.,
        'hip_yaw_joint': 5.,
        'knee_joint': 5.,
        'ankle_pitch_joint': 3.,
        'ankle_roll_joint': 2.,

        'waist_yaw_joint': 5.,
        'waist_pitch_joint': 5.,
        'waist_roll_joint': 5.,

        '_': 2.,
    },
    TAU_LIMITS={
    },
)


atom2 = {
    'NAME': 'atom2',
    # 'URDF': 'atom_description/atom.urdf',
    'URDF': 'atom_description/atom_1.urdf',
    'DOF_NAMES': [
        'left_hip_pitch_joint', 'left_hip_roll_joint', 'left_hip_yaw_joint', 'left_knee_joint',
        'left_ankle_pitch_joint', 'left_ankle_roll_joint',
        'right_hip_pitch_joint', 'right_hip_roll_joint', 'right_hip_yaw_joint', 'right_knee_joint',
        'right_ankle_pitch_joint', 'right_ankle_roll_joint',
        'waist_yaw_joint',
        'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint',
        'left_elbow_pitch_joint', 'left_elbow_roll_joint', 'left_wrist_pitch_joint', 'left_wrist_yaw_joint',
        'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint',
        'right_elbow_pitch_joint', 'right_elbow_roll_joint', 'right_wrist_pitch_joint', 'right_wrist_yaw_joint',
        'head_yaw_joint', 'head_pitch_joint',
    ],
    'DOF_NAMES_STD': {
        'left_hip_pitch_joint': 'left_hip_pitch',
        'left_hip_roll_joint': 'left_hip_roll',
        'left_hip_yaw_joint': 'left_hip_yaw',
        'left_knee_joint': 'left_knee_pitch',
        'left_ankle_pitch_joint': 'left_ankle_pitch',
        'left_ankle_roll_joint': 'left_ankle_roll',
        'right_hip_pitch_joint': 'right_hip_pitch',
        'right_hip_roll_joint': 'right_hip_roll',
        'right_hip_yaw_joint': 'right_hip_yaw',
        'right_knee_joint': 'right_knee_pitch',
        'right_ankle_pitch_joint': 'right_ankle_pitch',
        'right_ankle_roll_joint': 'right_ankle_roll',
        'waist_yaw_joint': 'waist_yaw',
        'left_shoulder_pitch_joint': 'left_shoulder_pitch',
        'left_shoulder_roll_joint': 'left_shoulder_roll',
        'left_shoulder_yaw_joint': 'left_shoulder_yaw',
        'left_elbow_pitch_joint': 'left_elbow_pitch',
        'left_elbow_roll_joint': 'left_wrist_yaw',
        'left_wrist_pitch_joint': 'left_wrist_pitch',
        'left_wrist_yaw_joint': 'left_wrist_roll',
        'right_shoulder_pitch_joint': 'right_shoulder_pitch',
        'right_shoulder_roll_joint': 'right_shoulder_roll',
        'right_shoulder_yaw_joint': 'right_shoulder_yaw',
        'right_elbow_pitch_joint': 'right_elbow_pitch',
        'right_elbow_roll_joint': 'right_wrist_yaw',
        'right_wrist_pitch_joint': 'right_wrist_pitch',
        'right_wrist_yaw_joint': 'right_wrist_roll',
        'head_yaw_joint': 'head_yaw',
        'head_pitch_joint': 'head_pitch',
    },
    'KP': {
        # Left leg
        'left_hip_pitch_joint': 154.88,
        'left_hip_roll_joint': 100.37,
        'left_hip_yaw_joint': 52.16,
        'left_knee_joint': 115.49,
        'left_ankle_pitch_joint': 21.83,
        'left_ankle_roll_joint': 21.83,
        # Right leg
        'right_hip_pitch_joint': 154.88,
        'right_hip_roll_joint': 100.37,
        'right_hip_yaw_joint': 52.16,
        'right_knee_joint': 115.49,
        'right_ankle_pitch_joint': 21.83,
        'right_ankle_roll_joint': 21.83,

        'waist_yaw_joint': 300.0,

        'left_shoulder_pitch_joint': 80,
        'left_shoulder_roll_joint': 80,
        'left_shoulder_yaw_joint': 80,
        'left_elbow_pitch_joint': 80,
        'left_elbow_roll_joint': 80,
        'left_wrist_pitch_joint': 80,
        'left_wrist_yaw_joint': 80,

        'right_shoulder_pitch_joint': 80,
        'right_shoulder_roll_joint': 80,
        'right_shoulder_yaw_joint': 80,
        'right_elbow_pitch_joint': 80,
        'right_elbow_roll_joint': 80,
        'right_wrist_pitch_joint': 80,
        'right_wrist_yaw_joint': 80,

        'head_yaw_joint': 40.,
        'head_pitch_joint': 40.,
    },
    'KD': {
        # Left leg
        'left_hip_pitch_joint': 16.43,
        'left_hip_roll_joint': 10.65,
        'left_hip_yaw_joint': 5.53,
        'left_knee_joint': 12.25,
        'left_ankle_pitch_joint': 2.32,
        'left_ankle_roll_joint': 2.32,
        # Right leg
        'right_hip_pitch_joint': 16.43,
        'right_hip_roll_joint': 10.65,
        'right_hip_yaw_joint': 5.53,
        'right_knee_joint': 12.25,
        'right_ankle_pitch_joint': 2.32,
        'right_ankle_roll_joint': 2.32,

        'waist_yaw_joint': 20.0,

        'left_shoulder_pitch_joint': 2.,
        'left_shoulder_roll_joint': 2.,
        'left_shoulder_yaw_joint': 2.,
        'left_elbow_pitch_joint': 2.,
        'left_elbow_roll_joint': 2.,
        'left_wrist_pitch_joint': 2.,
        'left_wrist_yaw_joint': 2.,

        'right_shoulder_pitch_joint': 2.,
        'right_shoulder_roll_joint': 2.,
        'right_shoulder_yaw_joint': 2.,
        'right_elbow_pitch_joint': 2.,
        'right_elbow_roll_joint': 2.,
        'right_wrist_pitch_joint': 2.,
        'right_wrist_yaw_joint': 2.,

        'head_yaw_joint': 2.,
        'head_pitch_joint': 2.,
    },
    'Q_RESET': {
        # Left leg
        'left_hip_pitch_joint': -0.1,
        'left_hip_roll_joint': 0.0,
        'left_hip_yaw_joint': 0.0,
        'left_knee_joint': 0.3,
        'left_ankle_pitch_joint': -0.2,
        'left_ankle_roll_joint': 0.0,
        # Right leg
        'right_hip_pitch_joint': -0.1,
        'right_hip_roll_joint': 0.0,
        'right_hip_yaw_joint': 0.0,
        'right_knee_joint': 0.3,
        'right_ankle_pitch_joint': -0.2,
        'right_ankle_roll_joint': 0.0,

        'left_shoulder_roll_joint': 0.2,
        'right_shoulder_roll_joint': -0.2,
        'left_elbow_pitch_joint': 1.57,
        'right_elbow_pitch_joint': 1.57,
    },
    'TAU_LIMIT': [
        280.0, 308.0, 140.0, 360.0, 130.0, 130.0,
        280.0, 308.0, 140.0, 360.0, 130.0, 130.0,
        250.0,
        56.0, 36.0, 36.0, 36.0, 18.6, 18.6, 18.6,
        56.0, 36.0, 36.0, 36.0, 18.6, 18.6, 18.6,
        12.0, 12.0,
    ],
}

g1d23 = dict(
    NAME = 'g1d23',
    KP = [
        100.0, 100.0, 100.0, 150.0, 40.0, 40.0,
        100.0, 100.0, 100.0, 150.0, 40.0, 40.0,
        150.0, 150.0, 150.0,
        20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0,
        20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0,
    ],
    KD = [
        2., 2., 2., 4., 2., 2.,
        2., 2., 2., 4., 2., 2.,
        4., 4., 4.,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
    ],
    DOF_NAMES = [
        'left_hip_pitch_joint',
        'left_hip_roll_joint',
        'left_hip_yaw_joint',
        'left_knee_joint',
        'left_ankle_pitch_joint',
        'left_ankle_roll_joint',

        'right_hip_pitch_joint',
        'right_hip_roll_joint',
        'right_hip_yaw_joint',
        'right_knee_joint',
        'right_ankle_pitch_joint',
        'right_ankle_roll_joint',

        'waist_yaw_joint',
        None,
        None,

        'left_shoulder_pitch_joint',
        'left_shoulder_roll_joint',
        'left_shoulder_yaw_joint',
        'left_elbow_joint',
        'left_wrist_roll_joint',
        None,
        None,

        'right_shoulder_pitch_joint',
        'right_shoulder_roll_joint',
        'right_shoulder_yaw_joint',
        'right_elbow_joint',
        'right_wrist_roll_joint',
        None,
        None,
    ],
    DOF_NAMES_STD = {
        'left_hip_pitch_joint': 'left_hip_pitch',
        'left_hip_roll_joint': 'left_hip_roll',
        'left_hip_yaw_joint': 'left_hip_yaw',
        'left_knee_joint': 'left_knee_pitch',
        'left_ankle_pitch_joint': 'left_ankle_pitch',
        'left_ankle_roll_joint': 'left_ankle_roll',
        'right_hip_pitch_joint': 'right_hip_pitch',
        'right_hip_roll_joint': 'right_hip_roll',
        'right_hip_yaw_joint': 'right_hip_yaw',
        'right_knee_joint': 'right_knee_pitch',
        'right_ankle_pitch_joint': 'right_ankle_pitch',
        'right_ankle_roll_joint': 'right_ankle_roll',
        'waist_yaw_joint': 'waist_yaw',
        'waist_roll_joint': 'waist_roll',
        'waist_pitch_joint': 'waist_pitch',
        'left_shoulder_pitch_joint': 'left_shoulder_pitch',
        'left_shoulder_roll_joint': 'left_shoulder_roll',
        'left_shoulder_yaw_joint': 'left_shoulder_yaw',
        'left_elbow_joint': 'left_elbow_pitch',
        # 'left_wrist_roll_joint': 'left_wrist_roll',
        'left_wrist_roll_joint': 'left_wrist_yaw',
        'right_shoulder_pitch_joint': 'right_shoulder_pitch',
        'right_shoulder_roll_joint': 'right_shoulder_roll',
        'right_shoulder_yaw_joint': 'right_shoulder_yaw',
        'right_elbow_joint': 'right_elbow_pitch',
        # 'right_wrist_roll_joint': 'right_wrist_roll',
        'right_wrist_roll_joint': 'right_wrist_yaw',
    },
    URDF = 'g1_description/g1_23dof_rev_1_0.urdf'
)

humanoid = {
    'NAME': 'humanoid',
    'URDF': 'humanoid/humanoid_1.urdf',
    # 'URDF': 'humanoid/humanoid.urdf',
    'DOF_NAMES_STD': {
        'root_chest_joint1': 'waist_roll',
        'root_chest_joint2': 'waist_yaw',
        'root_chest_joint3': 'waist_pitch',
        'chest_neck_joint1': 'head_roll',
        'chest_neck_joint2': 'head_yaw',
        'chest_neck_joint3': 'head_pitch',
        'root_right_hip_joint1': 'right_hip_roll',
        'root_right_hip_joint2': 'right_hip_yaw',
        'root_right_hip_joint3': 'right_hip_pitch',
        'right_knee': 'right_knee_pitch',
        'right_knee_right_ankle_joint1': 'ankle_roll',
        'right_knee_right_ankle_joint2': 'ankle_yaw',
        'right_knee_right_ankle_joint3': 'ankle_pitch',
        'chest_right_shoulder_joint1': 'right_shoulder_roll',
        'chest_right_shoulder_joint2': 'right_shoulder_yaw',
        'chest_right_shoulder_joint3': 'right_shoulder_pitch',
        'right_elbow': 'right_elbow_pitch',
        'root_left_hip_joint1': 'left_hip_roll',
        'root_left_hip_joint2': 'left_hip_yaw',
        'root_left_hip_joint3': 'left_hip_pitch',
        'left_knee': 'left_knee_pitch',
        'left_knee_left_ankle_joint1': 'left_ankle_roll',
        'left_knee_left_ankle_joint2': 'left_ankle_yaw',
        'left_knee_left_ankle_joint3': 'left_ankle_pitch',
        'chest_left_shoulder_joint1': 'left_shoulder_roll',
        'chest_left_shoulder_joint2': 'left_shoulder_yaw',
        'chest_left_shoulder_joint3': 'left_shoulder_pitch',
        'left_elbow': 'left_elbow_pitch'
    },
    'KP': {
        "hip": 600,
        "ankle": 25,
        "knee": 150,

        "root_chest": 300,
        "chest_neck": 50,

        "shoulder": 90,
        "elbow": 50,
        "wrist": 30,
    },
    'KD': {
        "hip": 40,
        "ankle": 5,
        "knee": 10,

        "root_chest": 20,
        "chest_neck": 5,

        "shoulder": 5,
        "elbow": 5,
        "wrist": 3,
    },
}
