# yapf: disable

hmn = {
    'NAME': 'humanoid',
    'URDF': 'humanoid/humanoid_1.urdf',
# URDF = 'humanoid/humanoid_lower.urdf'
}

adam = {
    'NAME': 'adam',
    'URDF': 'adam/adam_lite/urdf/adam_lite_1_1.urdf',
    'DOF_NAMES': [
        'hipPitch_Left',
        'hipRoll_Left',
        'hipYaw_Left',
        'kneePitch_Left',
        'anklePitch_Left',
        'ankleRoll_Left',
        'hipPitch_Right',
        'hipRoll_Right',
        'hipYaw_Right',
        'kneePitch_Right',
        'anklePitch_Right',
        'ankleRoll_Right',
        'waistRoll',
        'waistPitch',
        'waistYaw',
        'shoulderPitch_Left',
        'shoulderRoll_Left',
        'shoulderYaw_Left',
        'elbow_Left',
        'wristYaw_Left',
        'shoulderPitch_Right',
        'shoulderRoll_Right',
        'shoulderYaw_Right',
        'elbow_Right',
        'wristYaw_Right',
    ],
    'DOF_NAMES_STD': {
        'hipPitch_Left': 'left_hip_pitch',
        'hipRoll_Left': 'left_hip_roll',
        'hipYaw_Left': 'left_hip_yaw',
        'kneePitch_Left': 'left_knee_pitch',
        'anklePitch_Left': 'left_ankle_pitch',
        'ankleRoll_Left': 'left_ankle_roll',
        'hipPitch_Right': 'right_hip_pitch',
        'hipRoll_Right': 'right_hip_roll',
        'hipYaw_Right': 'right_hip_yaw',
        'kneePitch_Right': 'right_knee_pitch',
        'anklePitch_Right': 'right_ankle_pitch',
        'ankleRoll_Right': 'right_ankle_roll',
        'waistRoll': 'waist_roll',
        'waistPitch': 'waist_pitch',
        'waistYaw': 'waist_yaw',
        'shoulderPitch_Left': 'left_shoulder_pitch',
        'shoulderRoll_Left': 'left_shoulder_roll',
        'shoulderYaw_Left': 'left_shoulder_yaw',
        'elbow_Left': 'left_elbow_pitch',
        'wristYaw_Left': 'left_wrist_yaw',
        'shoulderPitch_Right': 'right_shoulder_pitch',
        'shoulderRoll_Right': 'right_shoulder_roll',
        'shoulderYaw_Right': 'right_shoulder_yaw',
        'elbow_Right': 'right_elbow_pitch',
        'wristYaw_Right': 'right_wrist_yaw',
    },
    'KP': [
        305.0, 700.0, 405.0, 305.0, 20.0, 10.0,
        305.0, 700.0, 405.0, 305.0, 20.0, 10.0,
        # 305.0, 700.0, 405.0, 305.0, 30.0, 0.0,
        # 305.0, 700.0, 405.0, 305.0, 30.0, 0.0,
        405.0, 405.0, 205.0,
        18.0, 9.0, 9.0, 9.0, 7.0,
        18.0, 9.0, 9.0, 9.0, 7.0,
    ],
    'KD': [
        6.1, 30.0, 6.1, 6.1, 1.25, 1.0,
        6.1, 30.0, 6.1, 6.1, 1.25, 1.0,
        # 6.1, 30.0, 6.1, 6.1, 2.25, 0.25,
        # 6.1, 30.0, 6.1, 6.1, 2.25, 0.25,
        6.1, 6.1, 4.1,
        1.0, 1.0, 1.0, 1.0, 0.5,
        1.0, 1.0, 1.0, 1.0, 0.5,
    ],
}

t1 = {
    'NAME': 't1',
    'URDF': 'Booster-T1/T1_serial_simple_version.urdf',
    'DOF_NAMES_STD': {
        'AAHead_yaw': 'head_yaw',
        'Head_pitch': 'head_pitch',
        'Waist': 'waist_yaw',
        'Left_Ankle_Pitch': 'left_ankle_pitch',
        'Left_Ankle_Roll': 'left_ankle_roll',
        'Left_Hip_Pitch': 'left_hip_pitch',
        'Left_Hip_Roll': 'left_hip_roll',
        'Left_Hip_Yaw': 'left_hip_yaw',
        'Left_Knee_Pitch': 'left_knee_pitch',
        # 'Left_Elbow_Pitch': 'left_elbow_pitch',
        'Left_Elbow_Pitch': 'left_shoulder_yaw',
        # 'Left_Elbow_Yaw': 'left_elbow_yaw',
        'Left_Elbow_Yaw': 'left_elbow_pitch',
        'Left_Shoulder_Pitch': 'left_shoulder_pitch',
        'Left_Shoulder_Roll': 'left_shoulder_roll',
        'Right_Ankle_Pitch': 'right_ankle_pitch',
        'Right_Ankle_Roll': 'right_ankle_roll',
        'Right_Hip_Pitch': 'right_hip_pitch',
        'Right_Hip_Roll': 'right_hip_roll',
        'Right_Hip_Yaw': 'right_hip_yaw',
        'Right_Knee_Pitch': 'right_knee_pitch',
        # 'Right_Elbow_Pitch': 'right_elbow_pitch',
        'Right_Elbow_Pitch': 'right_shoulder_yaw',
        # 'Right_Elbow_Yaw': 'right_elbow_yaw',
        'Right_Elbow_Yaw': 'right_elbow_pitch',
        'Right_Shoulder_Pitch': 'right_shoulder_pitch',
        'Right_Shoulder_Roll': 'right_shoulder_roll',
    },
    'KP': {
        'AAHead_yaw': 50,
        'Head_pitch': 50,
        'Waist': 100,
        # left-lower
        'Ankle_Pitch': 40,
        'Ankle_Roll': 30,
        'Hip_Pitch': 85,
        'Hip_Roll': 55,
        'Hip_Yaw': 55,
        'Knee_Pitch': 110,
        # left-upper
        'Elbow_Pitch': 33.75,
        'Elbow_Yaw': 33.75,
        'Shoulder_Pitch': 33.75,
        'Shoulder_Roll': 33.75,
    },
    'KD': {
        'AAHead_yaw': 0.5,
        'Head_pitch': 0.5,
        'Waist': 1.0,
        # left-lower
        'Ankle_Pitch': 0.5,
        'Ankle_Roll': 0.4,
        'Hip_Pitch': 1.25,
        'Hip_Roll': 0.75,
        'Hip_Yaw': 0.75,
        'Knee_Pitch': 1.5,
        # left-upper
        'Elbow_Pitch': 0.45,
        'Elbow_Yaw': 0.45,
        'Shoulder_Pitch': 0.45,
        'Shoulder_Roll': 0.45,
    },
    'Q_RESET': {
        'AAHead_yaw': 0,
        'Head_pitch': 0,
        'Waist': 0,
        # left-lower
        'Left_Ankle_Pitch': -0.29,
        'Left_Ankle_Roll': 0,
        'Left_Hip_Pitch': -0.25,
        'Left_Hip_Roll': 0,
        'Left_Hip_Yaw': 0,
        'Left_Knee_Pitch': 0.55,
        # left-upper
        'Left_Elbow_Pitch': 0,
        # 'Left_Elbow_Yaw': -1.6,
        'Left_Elbow_Yaw': 0.,
        'Left_Shoulder_Pitch': 0.5,
        'Left_Shoulder_Roll': -1.4,
        # right-lower
        'Right_Ankle_Pitch': -0.29,
        'Right_Ankle_Roll': 0,
        'Right_Hip_Pitch': -0.25,
        'Right_Hip_Roll': 0,
        'Right_Hip_Yaw': 0,
        'Right_Knee_Pitch': 0.55,
        # right-upper
        'Right_Elbow_Pitch': 0,
        # 'Right_Elbow_Yaw': 1.6,
        'Right_Elbow_Yaw': 0.,
        'Right_Shoulder_Pitch': 0.5,
        'Right_Shoulder_Roll': 1.4,
    },
}

dobot = {
    'NAME': 'dobot',
    'URDF': 'dobot/urdf/dobot_simplified_hand.urdf',
}

pm = {
    'NAME': 'pm',
    'URDF': 'pm/urdf/serial_pm_v2.urdf',
}

n1 = {
    'NAME': 'n1',
    'URDF': 'N1/urdf/N1_raw_1.urdf',
}

s42 = {
    'NAME': 's42',
    'MJCF': 'kuavo_s42/mjcf/biped_s42.xml',
    'DOF_NAMES_STD': {
        'leg_l1_joint': 'left_hip_roll',
        'leg_l2_joint': 'left_hip_yaw',
        'leg_l3_joint': 'left_hip_pitch',
        'leg_l4_joint': 'left_knee_pitch',
        'leg_l5_joint': 'left_ankle_pitch',
        'leg_l6_joint': 'left_ankle_roll',
        'leg_r1_joint': 'right_hip_roll',
        'leg_r2_joint': 'right_hip_yaw',
        'leg_r3_joint': 'right_hip_pitch',
        'leg_r4_joint': 'right_knee_pitch',
        'leg_r5_joint': 'right_ankle_pitch',
        'leg_r6_joint': 'right_ankle_roll',
        'zarm_l1_joint': 'left_shoulder_pitch',
        'zarm_l2_joint': 'left_shoulder_roll',
        'zarm_l3_joint': 'left_shoulder_yaw',
        'zarm_l4_joint': 'left_elbow_pitch',
        'zarm_l5_joint': 'left_wrist_yaw',
        'zarm_l6_joint': 'left_wrist_pitch',
        'zarm_l7_joint': 'left_wrist_roll',
        'zarm_r1_joint': 'right_shoulder_pitch',
        'zarm_r2_joint': 'right_shoulder_roll',
        'zarm_r3_joint': 'right_shoulder_yaw',
        'zarm_r4_joint': 'right_elbow_pitch',
        'zarm_r5_joint': 'right_wrist_yaw',
        'zarm_r6_joint': 'right_wrist_pitch',
        'zarm_r7_joint': 'right_wrist_roll',
    },
    'KP': {
        'leg_l1_joint': 60.0, 'leg_l2_joint': 60.0, 'leg_l3_joint': 60.0, 'leg_l4_joint': 60.0, 'leg_l5_joint': 30.0, 'leg_l6_joint': 15.0,
        'leg_r1_joint': 60.0, 'leg_r2_joint': 60.0, 'leg_r3_joint': 60.0, 'leg_r4_joint': 60.0, 'leg_r5_joint': 30.0, 'leg_r6_joint': 15.0,
        'zarm_l1_joint': 15.0, 'zarm_l2_joint': 15.0, 'zarm_l3_joint': 15.0, 'zarm_l4_joint': 15.0, 'zarm_l5_joint': 15.0, 'zarm_l6_joint': 15.0, 'zarm_l7_joint': 15.0,
        'zarm_r1_joint': 15.0, 'zarm_r2_joint': 15.0, 'zarm_r3_joint': 15.0, 'zarm_r4_joint': 15.0, 'zarm_r5_joint': 15.0, 'zarm_r6_joint': 15.0, 'zarm_r7_joint': 15.0
    },
    'KD': {
        'leg_l1_joint': 10.0, 'leg_l2_joint': 6.0, 'leg_l3_joint': 12.0, 'leg_l4_joint': 12.0, 'leg_l5_joint': 22.0, 'leg_l6_joint': 22.0,
        'leg_r1_joint': 10.0, 'leg_r2_joint': 6.0, 'leg_r3_joint': 12.0, 'leg_r4_joint': 12.0, 'leg_r5_joint': 22.0, 'leg_r6_joint': 22.0,
        'zarm_l1_joint': 3, 'zarm_l2_joint': 3, 'zarm_l3_joint': 3, 'zarm_l4_joint': 3, 'zarm_l5_joint': 3, 'zarm_l6_joint': 3, 'zarm_l7_joint': 3,
        'zarm_r1_joint': 3, 'zarm_r2_joint': 3, 'zarm_r3_joint': 3, 'zarm_r4_joint': 3, 'zarm_r5_joint': 3, 'zarm_r6_joint': 3, 'zarm_r7_joint': 3
    }
}
