# yapf: disable

hmn = {
    'NAME': 'humanoid',
    'URDF': 'humanoid/humanoid_1.urdf',
# URDF = 'humanoid/humanoid_lower.urdf'
}

adam = {
    'NAME': 'adam',
    'URDF': 'adam/adam_lite/urdf/adam_lite_1_1.urdf',
    # 'URDF': 'adam/adam_lite/urdf/adam_lite_1_2.urdf',
    'DOF_NAMES': [
        'hipPitch_Left',
        'hipRoll_Left',
        'hipYaw_Left',
        'kneePitch_Left',
        'anklePitch_Left',
        'ankleRoll_Left',
        'hipPitch_Right',
        'hipRoll_Right',
        'hipYaw_Right',
        'kneePitch_Right',
        'anklePitch_Right',
        'ankleRoll_Right',
        'waistRoll',
        'waistPitch',
        'waistYaw',
        'shoulderPitch_Left',
        'shoulderRoll_Left',
        'shoulderYaw_Left',
        'elbow_Left',
        'wristYaw_Left',
        'shoulderPitch_Right',
        'shoulderRoll_Right',
        'shoulderYaw_Right',
        'elbow_Right',
        'wristYaw_Right',
    ],
    'DOF_NAMES_STD': {
        'hipPitch_Left': 'left_hip_pitch',
        'hipRoll_Left': 'left_hip_roll',
        'hipYaw_Left': 'left_hip_yaw',
        'kneePitch_Left': 'left_knee_pitch',
        'anklePitch_Left': 'left_ankle_pitch',
        'ankleRoll_Left': 'left_ankle_roll',
        'hipPitch_Right': 'right_hip_pitch',
        'hipRoll_Right': 'right_hip_roll',
        'hipYaw_Right': 'right_hip_yaw',
        'kneePitch_Right': 'right_knee_pitch',
        'anklePitch_Right': 'right_ankle_pitch',
        'ankleRoll_Right': 'right_ankle_roll',
        'waistRoll': 'waist_roll',
        'waistPitch': 'waist_pitch',
        'waistYaw': 'waist_yaw',
        'shoulderPitch_Left': 'left_shoulder_pitch',
        'shoulderRoll_Left': 'left_shoulder_roll',
        'shoulderYaw_Left': 'left_shoulder_yaw',
        'elbow_Left': 'left_elbow_pitch',
        'wristYaw_Left': 'left_wrist_yaw',
        'shoulderPitch_Right': 'right_shoulder_pitch',
        'shoulderRoll_Right': 'right_shoulder_roll',
        'shoulderYaw_Right': 'right_shoulder_yaw',
        'elbow_Right': 'right_elbow_pitch',
        'wristYaw_Right': 'right_wrist_yaw',
    },
    'KP': [
        305.0, 700.0, 405.0, 305.0, 20.0, 10.0,
        305.0, 700.0, 405.0, 305.0, 20.0, 10.0,
        # 305.0, 700.0, 405.0, 305.0, 30.0, 0.0,
        # 305.0, 700.0, 405.0, 305.0, 30.0, 0.0,
        405.0, 405.0, 205.0,
        18.0, 9.0, 9.0, 9.0, 7.0,
        18.0, 9.0, 9.0, 9.0, 7.0,
    ],
    'KD': [
        6.1, 30.0, 6.1, 6.1, 1.25, 1.0,
        6.1, 30.0, 6.1, 6.1, 1.25, 1.0,
        # 6.1, 30.0, 6.1, 6.1, 2.25, 0.25,
        # 6.1, 30.0, 6.1, 6.1, 2.25, 0.25,
        6.1, 6.1, 4.1,
        1.0, 1.0, 1.0, 1.0, 0.5,
        1.0, 1.0, 1.0, 1.0, 0.5,
    ],
    'ASSET_OPTIONS': {
        'flip_visual_attachments': True,
    },
    'MOTOR_IPS': [
        '10.10.10.90',
        '10.10.10.91',
        '10.10.10.92',
        '10.10.10.50',
        '10.10.10.51',
        '10.10.10.52',
        '10.10.10.53',
        '10.10.10.54',
        '10.10.10.55',
        '10.10.10.70',
        '10.10.10.71',
        '10.10.10.72',
        '10.10.10.73',
        '10.10.10.74',
        '10.10.10.75',
        '10.10.10.10',
        '10.10.10.11',
        '10.10.10.12',
        '10.10.10.13',
        '10.10.10.14',
        # '10.10.10.15',
        # '10.10.10.16',
        '10.10.10.30',
        '10.10.10.31',
        '10.10.10.32',
        '10.10.10.33',
        '10.10.10.34',
        # '10.10.10.35',
        # '10.10.10.36',
    ],
}

t1 = {
    'NAME': 't1',
    # 'URDF': 'Booster-T1/T1_serial_simple_version.urdf',
    # 'URDF': 'T1/T1_locomotion.urdf',
    'URDF': 'T1/T1_serial.urdf',
    'DOF_NAMES_STD': {
        'AAHead_yaw': 'head_yaw',
        'Head_pitch': 'head_pitch',
        'Waist': 'waist_yaw',
        'Left_Ankle_Pitch': 'left_ankle_pitch',
        'Left_Ankle_Roll': 'left_ankle_roll',
        'Left_Hip_Pitch': 'left_hip_pitch',
        'Left_Hip_Roll': 'left_hip_roll',
        'Left_Hip_Yaw': 'left_hip_yaw',
        'Left_Knee_Pitch': 'left_knee_pitch',
        # 'Left_Elbow_Pitch': 'left_elbow_pitch',
        'Left_Elbow_Pitch': 'left_shoulder_yaw',
        # 'Left_Elbow_Yaw': 'left_elbow_yaw',
        'Left_Elbow_Yaw': 'left_elbow_pitch',
        'Left_Shoulder_Pitch': 'left_shoulder_pitch',
        'Left_Shoulder_Roll': 'left_shoulder_roll',
        'Right_Ankle_Pitch': 'right_ankle_pitch',
        'Right_Ankle_Roll': 'right_ankle_roll',
        'Right_Hip_Pitch': 'right_hip_pitch',
        'Right_Hip_Roll': 'right_hip_roll',
        'Right_Hip_Yaw': 'right_hip_yaw',
        'Right_Knee_Pitch': 'right_knee_pitch',
        # 'Right_Elbow_Pitch': 'right_elbow_pitch',
        'Right_Elbow_Pitch': 'right_shoulder_yaw',
        # 'Right_Elbow_Yaw': 'right_elbow_yaw',
        'Right_Elbow_Yaw': 'right_elbow_pitch',
        'Right_Shoulder_Pitch': 'right_shoulder_pitch',
        'Right_Shoulder_Roll': 'right_shoulder_roll',
    },
    'KP': [
        20, 20,
        20, 20, 20, 20,
        20, 20, 20, 20,
        200,
        200, 200, 200, 200, 50, 50,
        200, 200, 200, 200, 50, 50,
    ],
    'KD': [
        0.2, 0.2,
        0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5,
        5,
        5, 5, 5, 5, 3, 3,
        5, 5, 5, 5, 3, 3
    ],
    # 'KP': {
    #     'AAHead_yaw': 50,
    #     'Head_pitch': 50,
    #     'Waist': 100,
    #     # left-lower
    #     'Ankle_Pitch': 40,
    #     'Ankle_Roll': 30,
    #     'Hip_Pitch': 85,
    #     'Hip_Roll': 55,
    #     'Hip_Yaw': 55,
    #     'Knee_Pitch': 110,
    #     # left-upper
    #     'Elbow_Pitch': 33.75,
    #     'Elbow_Yaw': 33.75,
    #     'Shoulder_Pitch': 33.75,
    #     'Shoulder_Roll': 33.75,
    # },
    # 'KD': {
    #     'AAHead_yaw': 0.5,
    #     'Head_pitch': 0.5,
    #     'Waist': 1.0,
    #     # left-lower
    #     'Ankle_Pitch': 0.5,
    #     'Ankle_Roll': 0.4,
    #     'Hip_Pitch': 1.25,
    #     'Hip_Roll': 0.75,
    #     'Hip_Yaw': 0.75,
    #     'Knee_Pitch': 1.5,
    #     # left-upper
    #     'Elbow_Pitch': 0.45,
    #     'Elbow_Yaw': 0.45,
    #     'Shoulder_Pitch': 0.45,
    #     'Shoulder_Roll': 0.45,
    # },
    'Q_RESET': {
        'AAHead_yaw': 0,
        'Head_pitch': 0,
        'Waist': 0,
        # left-lower
        'Left_Ankle_Pitch': -0.29,
        'Left_Ankle_Roll': 0,
        'Left_Hip_Pitch': -0.25,
        'Left_Hip_Roll': 0,
        'Left_Hip_Yaw': 0,
        'Left_Knee_Pitch': 0.55,
        # left-upper
        'Left_Elbow_Pitch': 0,
        # 'Left_Elbow_Yaw': -1.6,
        'Left_Elbow_Yaw': 0.,
        'Left_Shoulder_Pitch': 0.5,
        'Left_Shoulder_Roll': -1.4,
        # right-lower
        'Right_Ankle_Pitch': -0.29,
        'Right_Ankle_Roll': 0,
        'Right_Hip_Pitch': -0.25,
        'Right_Hip_Roll': 0,
        'Right_Hip_Yaw': 0,
        'Right_Knee_Pitch': 0.55,
        # right-upper
        'Right_Elbow_Pitch': 0,
        # 'Right_Elbow_Yaw': 1.6,
        'Right_Elbow_Yaw': 0.,
        'Right_Shoulder_Pitch': 0.5,
        'Right_Shoulder_Roll': 1.4,
    },
}

dobot = {
    'NAME': 'dobot',
    'URDF': 'dobot/urdf/dobot_simplified_hand.urdf',
}

pm = {
    'NAME': 'pm',
    'URDF': 'pm/urdf/serial_pm_v2_proc.urdf',
    'DOF_NAMES_STD': {
        'J00_HIP_PITCH_L': 'left_hip_pitch',
        'J01_HIP_ROLL_L': 'left_hip_roll',
        'J02_HIP_YAW_L': 'left_hip_yaw',
        'J03_KNEE_PITCH_L': 'left_knee_pitch',
        'J04_ANKLE_PITCH_L': 'left_ankle_pitch',
        'J05_ANKLE_ROLL_L': 'left_ankle_roll',
        'J06_HIP_PITCH_R': 'right_hip_pitch',
        'J07_HIP_ROLL_R': 'right_hip_roll',
        'J08_HIP_YAW_R': 'right_hip_yaw',
        'J09_KNEE_PITCH_R': 'right_knee_pitch',
        'J10_ANKLE_PITCH_R': 'right_ankle_pitch',
        'J11_ANKLE_ROLL_R': 'right_ankle_roll',
        'J12_WAIST_YAW': 'waist_yaw',
        'J13_SHOULDER_PITCH_L': 'left_shoulder_pitch',
        'J14_SHOULDER_ROLL_L': 'left_shoulder_roll',
        'J15_SHOULDER_YAW_L': 'left_shoulder_yaw',
        'J16_ELBOW_PITCH_L': 'left_elbow_pitch',
        'J17_ELBOW_YAW_L': 'left_wrist_yaw',
        'J18_SHOULDER_PITCH_R': 'right_shoulder_pitch',
        'J19_SHOULDER_ROLL_R': 'right_shoulder_roll',
        'J20_SHOULDER_YAW_R': 'right_shoulder_yaw',
        'J21_ELBOW_PITCH_R': 'right_elbow_pitch',
        'J22_ELBOW_YAW_R': 'right_wrist_yaw',
        'J23_HEAD_YAW': 'head_yaw',
    },
    'KP': {
        'HIP_YAW': 100,
        'HIP_ROLL': 170,
        'HIP_PITCH': 300,
        'KNEE': 350,
        'ANKLE': 50,
        'WAIST_YAW': 200,
        'SHOULDER_PITCH': 25,
        'SHOULDER_YAW': 25,
        'SHOULDER_ROLL': 25,
        'ELBOW': 25,
        'HEAD': 5,
        #  'wrist_roll': 10,
        # 29dof for pm
        #  'waist_roll': 300,
        #  'waist_pitch': 300,
        #  'wrist_yaw': 2,
        #  'wrist_pitch': 2,
    },
    'KD': {
        'HIP_YAW': 1.3,
        'HIP_ROLL': 2.3,
        'HIP_PITCH': 4,
        'KNEE': 4.5,
        'ANKLE': 2.4,
        'WAIST_YAW': 1.3,
        'SHOULDER_PITCH': 0.6,
        'SHOULDER_YAW': 0.6,
        'SHOULDER_ROLL': 0.6,
        'ELBOW': 0.6,
        #  'wrist_roll': 0.25,
        'HEAD': 0.3,
    },
}

s45 = {
    'NAME': 's45',
    'URDF': 'biped_s45/urdf/biped_s45_1.urdf',
    'DOF_NAMES': [
        'leg_l1_joint', 'leg_l2_joint', 'leg_l3_joint', 'leg_l4_joint',
        'leg_l5_joint',
        'leg_l6_joint',
        'leg_r1_joint', 'leg_r2_joint', 'leg_r3_joint', 'leg_r4_joint',
        'leg_r5_joint',
        'leg_r6_joint',
        'zarm_l1_joint', 'zarm_l2_joint', 'zarm_l3_joint', 'zarm_l4_joint', 'zarm_l5_joint', 'zarm_l6_joint', 'zarm_l7_joint',
        'zarm_r1_joint', 'zarm_r2_joint', 'zarm_r3_joint', 'zarm_r4_joint', 'zarm_r5_joint', 'zarm_r6_joint', 'zarm_r7_joint',
        'zhead_1_joint', 'zhead_2_joint'
    ],
    'DOF_NAMES_STD': {
        'leg_l1_joint': 'left_hip_roll',
        'leg_l2_joint': 'left_hip_yaw',
        'leg_l3_joint': 'left_hip_pitch',
        'leg_l4_joint': 'left_knee_pitch',
        'leg_l5_joint': 'left_ankle_pitch',
        'leg_l6_joint': 'left_ankle_roll',
        'leg_r1_joint': 'right_hip_roll',
        'leg_r2_joint': 'right_hip_yaw',
        'leg_r3_joint': 'right_hip_pitch',
        'leg_r4_joint': 'right_knee_pitch',
        'leg_r5_joint': 'right_ankle_pitch',
        'leg_r6_joint': 'right_ankle_roll',
        'zarm_l1_joint': 'left_shoulder_pitch',
        'zarm_l2_joint': 'left_shoulder_roll',
        'zarm_l3_joint': 'left_shoulder_yaw',
        'zarm_l4_joint': 'left_elbow_pitch',
        'zarm_l5_joint': 'left_wrist_yaw',
        'zarm_l6_joint': 'left_wrist_pitch',
        'zarm_l7_joint': 'left_wrist_roll',
        'zarm_r1_joint': 'right_shoulder_pitch',
        'zarm_r2_joint': 'right_shoulder_roll',
        'zarm_r3_joint': 'right_shoulder_yaw',
        'zarm_r4_joint': 'right_elbow_pitch',
        'zarm_r5_joint': 'right_wrist_yaw',
        'zarm_r6_joint': 'right_wrist_pitch',
        'zarm_r7_joint': 'right_wrist_roll',
        'zhead_1_joint': 'head_yaw',
        'zhead_2_joint': 'head_pitch',
    },
    'KP': {
        'leg_l1_joint': 60.0, 'leg_l2_joint': 60.0, 'leg_l3_joint': 60.0, 'leg_l4_joint': 60.0, 'leg_l5_joint': 30.0, 'leg_l6_joint': 15.0,
        'leg_r1_joint': 60.0, 'leg_r2_joint': 60.0, 'leg_r3_joint': 60.0, 'leg_r4_joint': 60.0, 'leg_r5_joint': 30.0, 'leg_r6_joint': 15.0,
        'zarm_l1_joint': 15.0, 'zarm_l2_joint': 15.0, 'zarm_l3_joint': 15.0, 'zarm_l4_joint': 15.0, 'zarm_l5_joint': 15.0, 'zarm_l6_joint': 15.0, 'zarm_l7_joint': 15.0,
        'zarm_r1_joint': 15.0, 'zarm_r2_joint': 15.0, 'zarm_r3_joint': 15.0, 'zarm_r4_joint': 15.0, 'zarm_r5_joint': 15.0, 'zarm_r6_joint': 15.0, 'zarm_r7_joint': 15.0,
        'zhead_1_joint': 15.0, 'zhead_2_joint': 15.0,
    },
    'KD': {
        'leg_l1_joint': 10.0, 'leg_l2_joint': 6.0, 'leg_l3_joint': 12.0, 'leg_l4_joint': 12.0, 'leg_l5_joint': 22.0, 'leg_l6_joint': 22.0,
        'leg_r1_joint': 10.0, 'leg_r2_joint': 6.0, 'leg_r3_joint': 12.0, 'leg_r4_joint': 12.0, 'leg_r5_joint': 22.0, 'leg_r6_joint': 22.0,
        'zarm_l1_joint': 3, 'zarm_l2_joint': 3, 'zarm_l3_joint': 3, 'zarm_l4_joint': 3, 'zarm_l5_joint': 3, 'zarm_l6_joint': 3, 'zarm_l7_joint': 3,
        'zarm_r1_joint': 3, 'zarm_r2_joint': 3, 'zarm_r3_joint': 3, 'zarm_r4_joint': 3, 'zarm_r5_joint': 3, 'zarm_r6_joint': 3, 'zarm_r7_joint': 3,
        'zhead_1_joint': 3.0, 'zhead_2_joint': 3.0,
    },
    'TAU_LIMIT': {
        'leg_l1_joint': 110.0, 'leg_l2_joint': 110.0, 'leg_l3_joint': 110.0, 'leg_l4_joint': 110.0, 'leg_l5_joint': 18.0, 'leg_l6_joint': 18.0,
        'leg_r1_joint': 110.0, 'leg_r2_joint': 110.0, 'leg_r3_joint': 110.0, 'leg_r4_joint': 110.0, 'leg_r5_joint': 18.0, 'leg_r6_joint': 18.0,
        'zarm_l1_joint': 110.0, 'zarm_l2_joint': 18, 'zarm_l3_joint': 18, 'zarm_l4_joint': 18, 'zarm_l5_joint': 18, 'zarm_l6_joint': 18, 'zarm_l7_joint': 18,
        'zarm_r1_joint': 110.0, 'zarm_r2_joint': 18, 'zarm_r3_joint': 18, 'zarm_r4_joint': 18, 'zarm_r5_joint': 18, 'zarm_r6_joint': 18, 'zarm_r7_joint': 18,
        'zhead_1_joint': 10.0, 'zhead_2_joint': 10.0,
    },
    'Q_CTRL_MAX': {
        'leg_l3_joint': 0.7,
        'leg_r3_joint': 0.7,
    }
}

s42 = s45.copy()
s42['NAME'] = 's42'
s42['URDF'] = 'biped_s42/urdf/biped_s42_1.urdf'

from unicon.defs import n1
grmini = dict(
    NAME='grmini',
    DOF_NAMES=n1.DOF_NAMES,
    DOF_NAMES_STD=n1.DOF_NAMES_STD,
    KP=n1.KP,
    KD=n1.KD,
    NUM_DOFS=n1.NUM_DOFS,
    URDF='GRMini1T1/urdf/GRMini1T1_full.urdf',
)

g1_23 = dict(
    NAME = 'g1_23',
    KP = [
        100.0, 100.0, 100.0, 150.0, 40.0, 40.0,
        100.0, 100.0, 100.0, 150.0, 40.0, 40.0,
        150.0,
        20.0, 20.0, 20.0, 20.0, 20.0,
        20.0, 20.0, 20.0, 20.0, 20.0,
    ],
    KD = [
        2., 2., 2., 4., 2., 2.,
        2., 2., 2., 4., 2., 2.,
        4.,
        0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5,
    ],
    Q_CTRL_MIN = [
        -2.5307, -0.5236, -2.7576, -0.087267, -0.87267, -0.2618,
        -2.5307, -0.5236, -2.7576, -0.087267, -0.87267, -0.2618,
        -2.618,
        -3.0892, -1.5882, -2.618, -1.0472, -1.9722221,
        -3.0892, -2.2515, -2.618, -1.0472, -1.9722221,
    ],
    Q_CTRL_MAX = [
        2.8798, 2.9671, 2.7576, 2.8798, 0.5236, 0.2618,
        2.8798, 2.9671, 2.7576, 2.8798, 0.5236, 0.2618,
        2.618,
        2.6704, 2.2515, 2.618, 2.0944, 1.9722221,
        2.6704, 1.5882, 2.618, 2.0944, 1.9722221,
    ],
    QD_LIMIT = [
        32., 20., 32., 20., 37., 37.,
        32., 20., 32., 20., 37., 37.,
        32.,
        37., 37., 37., 37., 37.,
        37., 37., 37., 37., 37.,
    ],
    TAU_LIMIT = [
        88., 139., 88., 139., 50., 50.,
        88., 139., 88., 139., 50., 50.,
        54.,
        54., 30., 30., 30., 30.,
        54., 30., 30., 30., 30.,
    ],
    DOF_NAMES = [
        'left_hip_pitch_joint',
        'left_hip_roll_joint',
        'left_hip_yaw_joint',
        'left_knee_joint',
        'left_ankle_pitch_joint',
        'left_ankle_roll_joint',

        'right_hip_pitch_joint',
        'right_hip_roll_joint',
        'right_hip_yaw_joint',
        'right_knee_joint',
        'right_ankle_pitch_joint',
        'right_ankle_roll_joint',

        'waist_yaw_joint',

        'left_shoulder_pitch_joint',
        'left_shoulder_roll_joint',
        'left_shoulder_yaw_joint',
        'left_elbow_joint',
        'left_wrist_roll_joint',

        'right_shoulder_pitch_joint',
        'right_shoulder_roll_joint',
        'right_shoulder_yaw_joint',
        'right_elbow_joint',
        'right_wrist_roll_joint',
    ],
    DOF_NAMES_STD = {
        'left_hip_pitch_joint': 'left_hip_pitch',
        'left_hip_roll_joint': 'left_hip_roll',
        'left_hip_yaw_joint': 'left_hip_yaw',
        'left_knee_joint': 'left_knee_pitch',
        'left_ankle_pitch_joint': 'left_ankle_pitch',
        'left_ankle_roll_joint': 'left_ankle_roll',
        'right_hip_pitch_joint': 'right_hip_pitch',
        'right_hip_roll_joint': 'right_hip_roll',
        'right_hip_yaw_joint': 'right_hip_yaw',
        'right_knee_joint': 'right_knee_pitch',
        'right_ankle_pitch_joint': 'right_ankle_pitch',
        'right_ankle_roll_joint': 'right_ankle_roll',
        'waist_yaw_joint': 'waist_yaw',
        'waist_roll_joint': 'waist_roll',
        'waist_pitch_joint': 'waist_pitch',
        'left_shoulder_pitch_joint': 'left_shoulder_pitch',
        'left_shoulder_roll_joint': 'left_shoulder_roll',
        'left_shoulder_yaw_joint': 'left_shoulder_yaw',
        'left_elbow_joint': 'left_elbow_pitch',
        # 'left_wrist_roll_joint': 'left_wrist_roll',
        'left_wrist_roll_joint': 'left_wrist_yaw',
        'right_shoulder_pitch_joint': 'right_shoulder_pitch',
        'right_shoulder_roll_joint': 'right_shoulder_roll',
        'right_shoulder_yaw_joint': 'right_shoulder_yaw',
        'right_elbow_joint': 'right_elbow_pitch',
        # 'right_wrist_roll_joint': 'right_wrist_roll',
        'right_wrist_roll_joint': 'right_wrist_yaw',
    },
    URDF = 'g1_description/g1_23dof_rev_1_0.urdf'
)
